// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQCI7SNYT1DwLdEj6W5RKnBdgTVUokOCo',
    appId: '1:977538971052:web:f4aba8cb12204f3b847609',
    messagingSenderId: '977538971052',
    projectId: 'resonate-app-6f0fb',
    authDomain: 'resonate-app-6f0fb.firebaseapp.com',
    storageBucket: 'resonate-app-6f0fb.firebasestorage.app',
    measurementId: 'G-1V798VDCFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsFMzpX_NOMsk9oWLn4jYWN3jV82ZN2Js',
    appId: '1:977538971052:android:27eda9374cc22e45847609',
    messagingSenderId: '977538971052',
    projectId: 'resonate-app-6f0fb',
    storageBucket: 'resonate-app-6f0fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2mW0iFkJoAtKpTv_mrnH6MJT3c3w-5nE',
    appId: '1:977538971052:ios:200cd0dc5bbcd2b6847609',
    messagingSenderId: '977538971052',
    projectId: 'resonate-app-6f0fb',
    storageBucket: 'resonate-app-6f0fb.firebasestorage.app',
    iosBundleId: 'com.example.resonate',
  );

}