syntax = "proto3";

package resonate.api; 

import "proto/common.proto";
import "proto/errors.proto";

option go_package = "github.com/dghwood/resonate/server/proto";

message ResponseInfo {
    bool success = 1; 
    string error_message = 2; 
    ErrorEnum error = 3;
}
message RequestInfo {
    string user_id = 1; 
    TokenMessage access_token = 2; 
}

// Used to refresh access tokens
message RefreshAuthMessage {
    message Request {
        RequestInfo request_info = 1; 
        TokenMessage refresh_token = 2; 
    }
    message Response {
        ResponseInfo response_info = 1;
        TokenMessage access_token = 2; 
    }
    Request request = 1;
    Response response = 2;
}

// Used to request login password 
message LoginRequestMessage {
    message Request {
        RequestInfo request_info = 1; 
        string email = 2; 
        string phone_number = 3;
    }
    message Response {
        ResponseInfo response_info = 1;
    }
    Request request = 1;
    Response response = 2;
}

message LoginUserMessage {
    message Request {
        RequestInfo request_info = 1; 
        string email = 2; 
        string password = 3;
        string phone_number = 4; 
    }
    message Response {
        ResponseInfo response_info = 1;
        TokenMessage access_token = 2; 
        TokenMessage refresh_token = 3;
        UserMessage user = 4; 
    }
    Request request = 1;
    Response response = 2;
}

message CreateUserMessage {
    message Request {
        RequestInfo request_info = 1; 
        UserMessage user = 2; 
    }
    message Response {
        ResponseInfo response_info = 1;
        UserMessage user = 2;
    }
    Request request = 1;
    Response response = 2;
}

message GetUserMessage {
    message Request {
        RequestInfo request_info = 1; 
        string user_id = 2; 
    }
    message Response {
        ResponseInfo response_info = 1;
        UserMessage user = 2; 
    }
    Request request = 1;
    Response response = 2;
}

message UpdateUserMessage {
    message Request {
        RequestInfo request_info = 1; 
        UserMessage user = 2; 
    }
    message Response {
        ResponseInfo response_info = 1;
        UserMessage user = 2; 
    }
    Request request = 1;
    Response response = 2;
}

message SearchMessage {
    message Request {
        RequestInfo request_info = 1; 
        string query = 2; 
    }
    message Response {
        ResponseInfo response_info = 1;
        SearchResultsMessage search_results = 2; 
    }
    Request request = 1;
    Response response = 2;
}

// This is primarily used for typeahead suggestions
message SearchTopMessage {
    message Request {
        RequestInfo request_info = 1; 
    }
    message Response {
        ResponseInfo response_info = 1; 
        SearchResultsMessage search_results = 2; 
    }

    Request request = 1; 
    Response response = 2; 
}

message GetPodcastMessage {
    message Request {
        RequestInfo request_info = 1; 
        string podcast_id = 2; 
    }
    message Response {
        ResponseInfo response_info = 1;
        PodcastMessage podcast = 2; 
    }
    Request request = 1;
    Response response = 2;
}

// Used for getting the next page 
message QueryCursor {
    // For datastore queries 
    string cursor = 1;
    // For limit / offset queries eg. SQL/Memory
    int32 offset = 2;
}

// Used to list the podcast episodes
message ListPodcastEpisodesMessage {
    message Request {
        RequestInfo request_info = 1; 
        string podcast_id = 2; 
        QueryCursor cursor = 3;
    }
    message Response {
        ResponseInfo response_info = 1;
        repeated EpisodeMessage episodes = 2; 
        // TODO(duncan): Am I using this? 
        PodcastMessage podcast = 3;
        QueryCursor cursor = 4;
    }
    Request request = 1;
    Response response = 2;
}

message GetEpisodeMessage {
    message Request {
        RequestInfo request_info = 1; 
        string episode_id = 2; 
    }
    message Response {
        ResponseInfo response_info = 1;
        EpisodeMessage episode = 2; 
    }
    Request request = 1;
    Response response = 2;
}

message AddSubscriptionMessage {
    message Request {
        RequestInfo request_info = 1; 
        UserSubscriptionMessage subscription = 2; 
    }
    message Response {
        ResponseInfo response_info = 1;
        UserSubscriptionMessage subscription = 2; 
    }
    Request request = 1;
    Response response = 2;
}
// Do I need this? Basically the same as Add 
message RemoveSubscriptionMessage {
    message Request {
        RequestInfo request_info = 1; 
        UserSubscriptionMessage subscription = 2; 
    }
    message Response {
        ResponseInfo response_info = 1;
        UserSubscriptionMessage subscription = 2; 
    }
    Request request = 1;
    Response response = 2;
}

message ListSubscriptionMessage {
    message Request {
        RequestInfo request_info = 1; 
        string user_id = 2; 
        bool include_podcasts = 3; 
        QueryCursor cursor = 4;
    }
    message Response {
        ResponseInfo response_info = 1;
        repeated UserSubscriptionMessage subscriptions = 2; 
        QueryCursor cursor = 3;
    }
    Request request = 1;
    Response response = 2;
}

message AddListenMessage {
    message Request {
        RequestInfo request_info = 1; 
        UserListenMessage listen = 2;  
    }
    message Response {
        ResponseInfo response_info = 1; 
        UserListenMessage listen = 2; 
    }

    Request request = 1; 
    Response response = 2; 
}

message RemoveListenMessage {
    message Request {
        RequestInfo request_info = 1; 
        UserListenMessage listen = 2;  
    }
    message Response {
        ResponseInfo response_info = 1; 
        UserListenMessage listen = 2; 
    }

    Request request = 1; 
    Response response = 2; 
}

message ListListenMessage {
    message Request {
        RequestInfo request_info = 1; 
        string user_id = 2; 
        // Return the episodes in the UserListenMessage 
        bool include_episodes = 3; 
        QueryCursor cursor = 4;
    }
    message Response {
        ResponseInfo response_info = 1; 
        repeated UserListenMessage listens = 2; 
        QueryCursor cursor = 5;
    }

    Request request = 1; 
    Response response = 2; 
}

message GetFeedMessage {
    message Request {
        RequestInfo request_info = 1; 
        string user_id = 2; 
        // Used for requesting the n+1 page of feed items
        int64 before_timestamp_ms = 3; 
    }
    message Response {
        ResponseInfo response_info = 1; 
        UserFeedMessage feed = 2; 
    }

    Request request = 1; 
    Response reponse = 2; 
}

message AddFollowMessage {
    message Request {
        RequestInfo request_info = 1; 
        UserFollowMessage follow = 2;  
    }
    message Response {
        ResponseInfo response_info = 1; 
        UserFollowMessage follow = 2; 
    }

    Request request = 1; 
    Response response = 2; 
}

message RemoveFollowMessage {
    message Request {
        RequestInfo request_info = 1; 
        UserFollowMessage follow = 2;  
    }
    message Response {
        ResponseInfo response_info = 1; 
        UserFollowMessage follow = 2; 
    }

    Request request = 1; 
    Response response = 2; 
}

message ListFollowMessage {
    message Request {
        RequestInfo request_info = 1; 
        string user_id = 2; 
        QueryCursor cursor = 3;
        bool include_users = 4; 
        // Whether or not to return following or followed users
        bool is_followed = 5;
    }
    message Response {
        ResponseInfo response_info = 1; 
        repeated UserFollowMessage follows = 2; 
        QueryCursor cursor = 3;
    }

    Request request = 1; 
    Response response = 2; 
}

message GetPublicUserMessage {
    message Request {
        RequestInfo request_info = 1; 
        string user_id = 2;
    }
    message Response {
        ResponseInfo response_info = 1; 
        PublicUserMessage user = 2; 
    }

    Request request = 1; 
    Response response = 2; 
}

message EditUserMessage {
    message Request {
        RequestInfo request_info = 1; 
        UserMessage user = 2;
    }
    message Response {
        ResponseInfo response_info = 1; 
        UserMessage user = 2;
    }

    Request request = 1; 
    Response response = 2; 
}

message RemoveUserMessage {
    message Request {
        RequestInfo request_info = 1; 
        string user_id = 2;
    }
    message Response {
        ResponseInfo response_info = 1; 
    }

    Request request = 1; 
    Response response = 2; 
}

message ListUserMessage {
    message Request {
        RequestInfo request_info = 1; 
        repeated string user_ids = 2; 
    }
    message Response {
        ResponseInfo response_info = 1; 
        repeated PublicUserMessage users = 2; 
    }

    Request request = 1; 
    Response response = 2; 
}

message UploadImageMessage {
    message Request {
        RequestInfo request_info = 1; 
        bytes image_bytes = 2;
    }
    message Response {
        ResponseInfo response_info = 1; 
        string image_url = 2;
    }

    Request request = 1; 
    Response response = 2; 
}

message FindContactsMessage {
    message Request {
        RequestInfo request_info = 1; 
        repeated string phone_numbers = 2;
        QueryCursor cursor = 3;
    }
    message Response {
        ResponseInfo response_info = 1; 
        repeated PublicUserMessage users = 2; 
        QueryCursor cursor = 3;
    }

    Request request = 1; 
    Response response = 2; 
}

message SearchContactsMessage {
    message Request {
        RequestInfo request_info = 1; 
        QueryCursor cursor = 2;
        string query = 3; 
    }
    message Response {
        ResponseInfo response_info = 1; 
        repeated PublicUserMessage users = 2; 
        QueryCursor cursor = 3;
    }
}

message SearchTopContactsMessage {
    message Request {
        RequestInfo request_info = 1; 
        repeated UserContactMessage contacts = 2;
    }
    message Response {
        ResponseInfo response_info = 1; 
        repeated PublicUserMessage users = 2; 
    }
}