/* Common Resonate Protos 

    * Create User 
    * Search Podcasts 
    * Show podcast details & episodes 
    * Subscribe to podcast 
    * Show subscription list 
    * Subscribed episodes show up in feed 
    * Listen to episodes 
    * Log episodes as listened
    * Search for users 
    * Show listened episodes & subscriptions
    * Follow users 
*/ 
syntax = "proto3";

package resonate; 

option go_package = "github.com/dghwood/resonate/proto"; 

message StorageMetadataMessage {
    bool is_deleted = 1;
    // In milliseconds since epoch, UTC time
    int64 updated_timestamp = 2; 
    // In milliseconds since epoch, UTC time
    int64 created_timestamp = 3;
}

message PodcastMessage {
    string id = 1;
    string title = 2;
    string description = 3;
    string url = 4;
    string image_url = 5;
    string author = 6;
    // this is optional 
    repeated EpisodeMessage episodes = 7;
    StorageMetadataMessage metadata = 8; 
}

message EpisodeMessage {
    string id = 1;
    string podcast_id = 2;
    string title = 3;
    string description = 4;
    string audio_url = 5;
    string image_url = 6;
    int64 publish_timestamp = 8;
    int64 duration_seconds = 9;
    int64 episode_number = 10;
    bool explicit = 11;
    StorageMetadataMessage metadata = 12; 
}

message TokenMessage {
    string token = 1; 
    // timestamp in seconds, UTC time
    int64 expiry_utc_timestamp = 2; 
}

message UserStorageMessage {
    UserMessage user = 1; 
    TokenMessage access_token = 2; 
    TokenMessage refresh_token = 3; 
}

message UserMessage {
    string id = 1;
    string name = 2;
    string email = 3;
    string image_url = 4;
    repeated UserSubscriptionMessage subscriptions = 5;
    repeated UserListenMessage listens = 6;
    repeated UserFollowMessage following = 7;
    int64 num_followers = 8; 
    StorageMetadataMessage metadata = 9; 
}

// Stripped down UserMessage for more public consumption
// eg. listens  
message PublicUserMessage {
    string id = 1; 
    string name = 2; 
    string image_url = 3; 
}

message UserFollowMessage {
    string user_id = 1; 
    string followed_user_id = 2;
    StorageMetadataMessage metadata = 3; 
}

message UserSubscriptionMessage {
    string id = 1;
    string user_id = 2;
    string podcast_id = 3;
    StorageMetadataMessage metadata = 4; 
}

message UserListenMessage {
    string id = 1; 
    string user_id = 2;
    string episode_id = 3;
    int64 listen_timestamp = 4;
    int64 seconds = 5;
    bool completed = 6;
    EpisodeMessage episode = 7; // this is optional, used for feed items

    StorageMetadataMessage metadata = 8;
}

message UserFeedItemEpisodeMessage {
    EpisodeMessage episode = 1;
    // These are social items relating to followed users
    repeated PublicUserMessage user_listens = 2;
} 
message UserFeedItemRecommendationMessage {
    EpisodeMessage episode = 1; 
    PodcastMessage podcast = 2; 
    repeated PublicUserMessage user_listens = 3;
    repeated PublicUserMessage user_subscriptions = 4;
}

message UserFeedItemMessage {
    UserFeedItemEpisodeMessage episode_item = 1; 
    repeated UserFeedItemRecommendationMessage recommended_items = 2; 
}

message UserFeedMessage {
    string user_id = 1; 
    repeated UserFeedItemMessage items = 2;
}

// Search Results 
message SearchResultMessage {
    // Only one of these should be filled out
    PodcastMessage podcast = 1; 
    UserMessage user = 2; 
    EpisodeMessage episode = 3; 
}
message SearchResultsMessage {
    repeated SearchResultMessage results = 1;
    // int64 num_results = 2; 
}

message UserDownloadMessage {
    string id = 1; 
    string episode_id = 2; 
    string file_path = 3; 
    bool is_downloaded = 4;

    StorageMetadataMessage metadata = 5; 
}