syntax = "proto3";

package resonate.logging; 

import "proto/api.proto";

option go_package = "github.com/dghwood/resonate/proto";

/* Logging Messages 

*/ 

// Next Tag: 9
message ApiEventMessage {
    int64 timestamp_usec = 1; 
    // Get this from "cloud.google.com/go/compute/metadata" on startup
    string instance_id = 8;
    // Need to add a binary version for the SERVER
    string binary_version = 9;
    string api_path = 2;
    resonate.api.RequestInfo request_info = 3; 
    resonate.api.ResponseInfo response_info = 4;
    // X-Cloud-Trace-Context header 
    string trace_id = 5;  
    // X-Forwarded-For
    string ips = 6; 
    // When the response was written
    int64 response_timestamp_usec = 7; 
}