// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseInfo) Reset() {
	*x = ResponseInfo{}
	mi := &file_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseInfo) ProtoMessage() {}

func (x *ResponseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseInfo.ProtoReflect.Descriptor instead.
func (*ResponseInfo) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseInfo) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RequestInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInfo) Reset() {
	*x = RequestInfo{}
	mi := &file_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInfo) ProtoMessage() {}

func (x *RequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInfo.ProtoReflect.Descriptor instead.
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *RequestInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestInfo) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// Used to refresh access tokens
type RefreshAuthMessage struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Request       *RefreshAuthMessage_Request  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response      *RefreshAuthMessage_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAuthMessage) Reset() {
	*x = RefreshAuthMessage{}
	mi := &file_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAuthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAuthMessage) ProtoMessage() {}

func (x *RefreshAuthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAuthMessage.ProtoReflect.Descriptor instead.
func (*RefreshAuthMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshAuthMessage) GetRequest() *RefreshAuthMessage_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RefreshAuthMessage) GetResponse() *RefreshAuthMessage_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

// Used to request login password
type LoginRequestMessage struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Request       *LoginRequestMessage_Request  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response      *LoginRequestMessage_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestMessage) Reset() {
	*x = LoginRequestMessage{}
	mi := &file_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestMessage) ProtoMessage() {}

func (x *LoginRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestMessage.ProtoReflect.Descriptor instead.
func (*LoginRequestMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequestMessage) GetRequest() *LoginRequestMessage_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *LoginRequestMessage) GetResponse() *LoginRequestMessage_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type LoginUserMessage struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Request       *LoginUserMessage_Request  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response      *LoginUserMessage_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserMessage) Reset() {
	*x = LoginUserMessage{}
	mi := &file_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserMessage) ProtoMessage() {}

func (x *LoginUserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserMessage.ProtoReflect.Descriptor instead.
func (*LoginUserMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *LoginUserMessage) GetRequest() *LoginUserMessage_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *LoginUserMessage) GetResponse() *LoginUserMessage_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type CreateUserMessage struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Request       *CreateUserMessage_Request  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response      *CreateUserMessage_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserMessage) Reset() {
	*x = CreateUserMessage{}
	mi := &file_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserMessage) ProtoMessage() {}

func (x *CreateUserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserMessage.ProtoReflect.Descriptor instead.
func (*CreateUserMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserMessage) GetRequest() *CreateUserMessage_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CreateUserMessage) GetResponse() *CreateUserMessage_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type GetUserMessage struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Request       *GetUserMessage_Request  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response      *GetUserMessage_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMessage) Reset() {
	*x = GetUserMessage{}
	mi := &file_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMessage) ProtoMessage() {}

func (x *GetUserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMessage.ProtoReflect.Descriptor instead.
func (*GetUserMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserMessage) GetRequest() *GetUserMessage_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GetUserMessage) GetResponse() *GetUserMessage_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type UpdateUserMessage struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Request       *UpdateUserMessage_Request  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response      *UpdateUserMessage_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserMessage) Reset() {
	*x = UpdateUserMessage{}
	mi := &file_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserMessage) ProtoMessage() {}

func (x *UpdateUserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserMessage.ProtoReflect.Descriptor instead.
func (*UpdateUserMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserMessage) GetRequest() *UpdateUserMessage_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *UpdateUserMessage) GetResponse() *UpdateUserMessage_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type SearchMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Request       *SearchMessage_Request  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response      *SearchMessage_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMessage) Reset() {
	*x = SearchMessage{}
	mi := &file_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessage) ProtoMessage() {}

func (x *SearchMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessage.ProtoReflect.Descriptor instead.
func (*SearchMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *SearchMessage) GetRequest() *SearchMessage_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *SearchMessage) GetResponse() *SearchMessage_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type GetPodcastMessage struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Request       *GetPodcastMessage_Request  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response      *GetPodcastMessage_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodcastMessage) Reset() {
	*x = GetPodcastMessage{}
	mi := &file_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodcastMessage) ProtoMessage() {}

func (x *GetPodcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodcastMessage.ProtoReflect.Descriptor instead.
func (*GetPodcastMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetPodcastMessage) GetRequest() *GetPodcastMessage_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GetPodcastMessage) GetResponse() *GetPodcastMessage_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type GetEpisodeMessage struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Request       *GetEpisodeMessage_Request  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response      *GetEpisodeMessage_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEpisodeMessage) Reset() {
	*x = GetEpisodeMessage{}
	mi := &file_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEpisodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEpisodeMessage) ProtoMessage() {}

func (x *GetEpisodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEpisodeMessage.ProtoReflect.Descriptor instead.
func (*GetEpisodeMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetEpisodeMessage) GetRequest() *GetEpisodeMessage_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GetEpisodeMessage) GetResponse() *GetEpisodeMessage_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type AddSubscriptionMessage struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Request       *AddSubscriptionMessage_Request  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response      *AddSubscriptionMessage_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSubscriptionMessage) Reset() {
	*x = AddSubscriptionMessage{}
	mi := &file_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSubscriptionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSubscriptionMessage) ProtoMessage() {}

func (x *AddSubscriptionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSubscriptionMessage.ProtoReflect.Descriptor instead.
func (*AddSubscriptionMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *AddSubscriptionMessage) GetRequest() *AddSubscriptionMessage_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AddSubscriptionMessage) GetResponse() *AddSubscriptionMessage_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type RemoveSubscriptionMessage struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Request       *RemoveSubscriptionMessage_Request  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response      *RemoveSubscriptionMessage_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSubscriptionMessage) Reset() {
	*x = RemoveSubscriptionMessage{}
	mi := &file_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSubscriptionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubscriptionMessage) ProtoMessage() {}

func (x *RemoveSubscriptionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubscriptionMessage.ProtoReflect.Descriptor instead.
func (*RemoveSubscriptionMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveSubscriptionMessage) GetRequest() *RemoveSubscriptionMessage_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RemoveSubscriptionMessage) GetResponse() *RemoveSubscriptionMessage_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type RefreshAuthMessage_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestInfo   *RequestInfo           `protobuf:"bytes,1,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAuthMessage_Request) Reset() {
	*x = RefreshAuthMessage_Request{}
	mi := &file_proto_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAuthMessage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAuthMessage_Request) ProtoMessage() {}

func (x *RefreshAuthMessage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAuthMessage_Request.ProtoReflect.Descriptor instead.
func (*RefreshAuthMessage_Request) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RefreshAuthMessage_Request) GetRequestInfo() *RequestInfo {
	if x != nil {
		return x.RequestInfo
	}
	return nil
}

func (x *RefreshAuthMessage_Request) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshAuthMessage_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseInfo  *ResponseInfo          `protobuf:"bytes,1,opt,name=response_info,json=responseInfo,proto3" json:"response_info,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAuthMessage_Response) Reset() {
	*x = RefreshAuthMessage_Response{}
	mi := &file_proto_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAuthMessage_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAuthMessage_Response) ProtoMessage() {}

func (x *RefreshAuthMessage_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAuthMessage_Response.ProtoReflect.Descriptor instead.
func (*RefreshAuthMessage_Response) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2, 1}
}

func (x *RefreshAuthMessage_Response) GetResponseInfo() *ResponseInfo {
	if x != nil {
		return x.ResponseInfo
	}
	return nil
}

func (x *RefreshAuthMessage_Response) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type LoginRequestMessage_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestInfo   *RequestInfo           `protobuf:"bytes,1,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestMessage_Request) Reset() {
	*x = LoginRequestMessage_Request{}
	mi := &file_proto_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestMessage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestMessage_Request) ProtoMessage() {}

func (x *LoginRequestMessage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestMessage_Request.ProtoReflect.Descriptor instead.
func (*LoginRequestMessage_Request) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *LoginRequestMessage_Request) GetRequestInfo() *RequestInfo {
	if x != nil {
		return x.RequestInfo
	}
	return nil
}

func (x *LoginRequestMessage_Request) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type LoginRequestMessage_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseInfo  *ResponseInfo          `protobuf:"bytes,1,opt,name=response_info,json=responseInfo,proto3" json:"response_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestMessage_Response) Reset() {
	*x = LoginRequestMessage_Response{}
	mi := &file_proto_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestMessage_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestMessage_Response) ProtoMessage() {}

func (x *LoginRequestMessage_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestMessage_Response.ProtoReflect.Descriptor instead.
func (*LoginRequestMessage_Response) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3, 1}
}

func (x *LoginRequestMessage_Response) GetResponseInfo() *ResponseInfo {
	if x != nil {
		return x.ResponseInfo
	}
	return nil
}

type LoginUserMessage_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestInfo   *RequestInfo           `protobuf:"bytes,1,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserMessage_Request) Reset() {
	*x = LoginUserMessage_Request{}
	mi := &file_proto_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserMessage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserMessage_Request) ProtoMessage() {}

func (x *LoginUserMessage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserMessage_Request.ProtoReflect.Descriptor instead.
func (*LoginUserMessage_Request) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{4, 0}
}

func (x *LoginUserMessage_Request) GetRequestInfo() *RequestInfo {
	if x != nil {
		return x.RequestInfo
	}
	return nil
}

func (x *LoginUserMessage_Request) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserMessage_Request) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserMessage_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseInfo  *ResponseInfo          `protobuf:"bytes,1,opt,name=response_info,json=responseInfo,proto3" json:"response_info,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	User          *UserMessage           `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserMessage_Response) Reset() {
	*x = LoginUserMessage_Response{}
	mi := &file_proto_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserMessage_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserMessage_Response) ProtoMessage() {}

func (x *LoginUserMessage_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserMessage_Response.ProtoReflect.Descriptor instead.
func (*LoginUserMessage_Response) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{4, 1}
}

func (x *LoginUserMessage_Response) GetResponseInfo() *ResponseInfo {
	if x != nil {
		return x.ResponseInfo
	}
	return nil
}

func (x *LoginUserMessage_Response) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginUserMessage_Response) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginUserMessage_Response) GetUser() *UserMessage {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserMessage_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestInfo   *RequestInfo           `protobuf:"bytes,1,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	User          *UserMessage           `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserMessage_Request) Reset() {
	*x = CreateUserMessage_Request{}
	mi := &file_proto_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserMessage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserMessage_Request) ProtoMessage() {}

func (x *CreateUserMessage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserMessage_Request.ProtoReflect.Descriptor instead.
func (*CreateUserMessage_Request) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CreateUserMessage_Request) GetRequestInfo() *RequestInfo {
	if x != nil {
		return x.RequestInfo
	}
	return nil
}

func (x *CreateUserMessage_Request) GetUser() *UserMessage {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserMessage_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseInfo  *ResponseInfo          `protobuf:"bytes,1,opt,name=response_info,json=responseInfo,proto3" json:"response_info,omitempty"`
	User          *UserMessage           `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserMessage_Response) Reset() {
	*x = CreateUserMessage_Response{}
	mi := &file_proto_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserMessage_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserMessage_Response) ProtoMessage() {}

func (x *CreateUserMessage_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserMessage_Response.ProtoReflect.Descriptor instead.
func (*CreateUserMessage_Response) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{5, 1}
}

func (x *CreateUserMessage_Response) GetResponseInfo() *ResponseInfo {
	if x != nil {
		return x.ResponseInfo
	}
	return nil
}

func (x *CreateUserMessage_Response) GetUser() *UserMessage {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserMessage_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestInfo   *RequestInfo           `protobuf:"bytes,1,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMessage_Request) Reset() {
	*x = GetUserMessage_Request{}
	mi := &file_proto_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMessage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMessage_Request) ProtoMessage() {}

func (x *GetUserMessage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMessage_Request.ProtoReflect.Descriptor instead.
func (*GetUserMessage_Request) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GetUserMessage_Request) GetRequestInfo() *RequestInfo {
	if x != nil {
		return x.RequestInfo
	}
	return nil
}

func (x *GetUserMessage_Request) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserMessage_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseInfo  *ResponseInfo          `protobuf:"bytes,1,opt,name=response_info,json=responseInfo,proto3" json:"response_info,omitempty"`
	User          *UserMessage           `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMessage_Response) Reset() {
	*x = GetUserMessage_Response{}
	mi := &file_proto_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMessage_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMessage_Response) ProtoMessage() {}

func (x *GetUserMessage_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMessage_Response.ProtoReflect.Descriptor instead.
func (*GetUserMessage_Response) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{6, 1}
}

func (x *GetUserMessage_Response) GetResponseInfo() *ResponseInfo {
	if x != nil {
		return x.ResponseInfo
	}
	return nil
}

func (x *GetUserMessage_Response) GetUser() *UserMessage {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserMessage_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestInfo   *RequestInfo           `protobuf:"bytes,1,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	User          *UserMessage           `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserMessage_Request) Reset() {
	*x = UpdateUserMessage_Request{}
	mi := &file_proto_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserMessage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserMessage_Request) ProtoMessage() {}

func (x *UpdateUserMessage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserMessage_Request.ProtoReflect.Descriptor instead.
func (*UpdateUserMessage_Request) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{7, 0}
}

func (x *UpdateUserMessage_Request) GetRequestInfo() *RequestInfo {
	if x != nil {
		return x.RequestInfo
	}
	return nil
}

func (x *UpdateUserMessage_Request) GetUser() *UserMessage {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserMessage_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseInfo  *ResponseInfo          `protobuf:"bytes,1,opt,name=response_info,json=responseInfo,proto3" json:"response_info,omitempty"`
	User          *UserMessage           `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserMessage_Response) Reset() {
	*x = UpdateUserMessage_Response{}
	mi := &file_proto_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserMessage_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserMessage_Response) ProtoMessage() {}

func (x *UpdateUserMessage_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserMessage_Response.ProtoReflect.Descriptor instead.
func (*UpdateUserMessage_Response) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{7, 1}
}

func (x *UpdateUserMessage_Response) GetResponseInfo() *ResponseInfo {
	if x != nil {
		return x.ResponseInfo
	}
	return nil
}

func (x *UpdateUserMessage_Response) GetUser() *UserMessage {
	if x != nil {
		return x.User
	}
	return nil
}

type SearchMessage_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestInfo   *RequestInfo           `protobuf:"bytes,1,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMessage_Request) Reset() {
	*x = SearchMessage_Request{}
	mi := &file_proto_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessage_Request) ProtoMessage() {}

func (x *SearchMessage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessage_Request.ProtoReflect.Descriptor instead.
func (*SearchMessage_Request) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8, 0}
}

func (x *SearchMessage_Request) GetRequestInfo() *RequestInfo {
	if x != nil {
		return x.RequestInfo
	}
	return nil
}

func (x *SearchMessage_Request) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchMessage_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseInfo  *ResponseInfo          `protobuf:"bytes,1,opt,name=response_info,json=responseInfo,proto3" json:"response_info,omitempty"`
	Podcasts      []*PodcastMessage      `protobuf:"bytes,2,rep,name=podcasts,proto3" json:"podcasts,omitempty"`
	Users         []*UserMessage         `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	Episodes      []*EpisodeMessage      `protobuf:"bytes,4,rep,name=episodes,proto3" json:"episodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMessage_Response) Reset() {
	*x = SearchMessage_Response{}
	mi := &file_proto_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessage_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessage_Response) ProtoMessage() {}

func (x *SearchMessage_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessage_Response.ProtoReflect.Descriptor instead.
func (*SearchMessage_Response) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8, 1}
}

func (x *SearchMessage_Response) GetResponseInfo() *ResponseInfo {
	if x != nil {
		return x.ResponseInfo
	}
	return nil
}

func (x *SearchMessage_Response) GetPodcasts() []*PodcastMessage {
	if x != nil {
		return x.Podcasts
	}
	return nil
}

func (x *SearchMessage_Response) GetUsers() []*UserMessage {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchMessage_Response) GetEpisodes() []*EpisodeMessage {
	if x != nil {
		return x.Episodes
	}
	return nil
}

type GetPodcastMessage_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestInfo   *RequestInfo           `protobuf:"bytes,1,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	PodcastId     string                 `protobuf:"bytes,2,opt,name=podcast_id,json=podcastId,proto3" json:"podcast_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodcastMessage_Request) Reset() {
	*x = GetPodcastMessage_Request{}
	mi := &file_proto_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodcastMessage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodcastMessage_Request) ProtoMessage() {}

func (x *GetPodcastMessage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodcastMessage_Request.ProtoReflect.Descriptor instead.
func (*GetPodcastMessage_Request) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GetPodcastMessage_Request) GetRequestInfo() *RequestInfo {
	if x != nil {
		return x.RequestInfo
	}
	return nil
}

func (x *GetPodcastMessage_Request) GetPodcastId() string {
	if x != nil {
		return x.PodcastId
	}
	return ""
}

type GetPodcastMessage_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseInfo  *ResponseInfo          `protobuf:"bytes,1,opt,name=response_info,json=responseInfo,proto3" json:"response_info,omitempty"`
	Podcast       *PodcastMessage        `protobuf:"bytes,2,opt,name=podcast,proto3" json:"podcast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodcastMessage_Response) Reset() {
	*x = GetPodcastMessage_Response{}
	mi := &file_proto_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodcastMessage_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodcastMessage_Response) ProtoMessage() {}

func (x *GetPodcastMessage_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodcastMessage_Response.ProtoReflect.Descriptor instead.
func (*GetPodcastMessage_Response) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{9, 1}
}

func (x *GetPodcastMessage_Response) GetResponseInfo() *ResponseInfo {
	if x != nil {
		return x.ResponseInfo
	}
	return nil
}

func (x *GetPodcastMessage_Response) GetPodcast() *PodcastMessage {
	if x != nil {
		return x.Podcast
	}
	return nil
}

type GetEpisodeMessage_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestInfo   *RequestInfo           `protobuf:"bytes,1,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	EpisodeId     string                 `protobuf:"bytes,2,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEpisodeMessage_Request) Reset() {
	*x = GetEpisodeMessage_Request{}
	mi := &file_proto_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEpisodeMessage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEpisodeMessage_Request) ProtoMessage() {}

func (x *GetEpisodeMessage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEpisodeMessage_Request.ProtoReflect.Descriptor instead.
func (*GetEpisodeMessage_Request) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{10, 0}
}

func (x *GetEpisodeMessage_Request) GetRequestInfo() *RequestInfo {
	if x != nil {
		return x.RequestInfo
	}
	return nil
}

func (x *GetEpisodeMessage_Request) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

type GetEpisodeMessage_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseInfo  *ResponseInfo          `protobuf:"bytes,1,opt,name=response_info,json=responseInfo,proto3" json:"response_info,omitempty"`
	Episode       *EpisodeMessage        `protobuf:"bytes,2,opt,name=episode,proto3" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEpisodeMessage_Response) Reset() {
	*x = GetEpisodeMessage_Response{}
	mi := &file_proto_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEpisodeMessage_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEpisodeMessage_Response) ProtoMessage() {}

func (x *GetEpisodeMessage_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEpisodeMessage_Response.ProtoReflect.Descriptor instead.
func (*GetEpisodeMessage_Response) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{10, 1}
}

func (x *GetEpisodeMessage_Response) GetResponseInfo() *ResponseInfo {
	if x != nil {
		return x.ResponseInfo
	}
	return nil
}

func (x *GetEpisodeMessage_Response) GetEpisode() *EpisodeMessage {
	if x != nil {
		return x.Episode
	}
	return nil
}

type AddSubscriptionMessage_Request struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	RequestInfo   *RequestInfo             `protobuf:"bytes,1,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	Subscription  *UserSubscriptionMessage `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSubscriptionMessage_Request) Reset() {
	*x = AddSubscriptionMessage_Request{}
	mi := &file_proto_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSubscriptionMessage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSubscriptionMessage_Request) ProtoMessage() {}

func (x *AddSubscriptionMessage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSubscriptionMessage_Request.ProtoReflect.Descriptor instead.
func (*AddSubscriptionMessage_Request) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{11, 0}
}

func (x *AddSubscriptionMessage_Request) GetRequestInfo() *RequestInfo {
	if x != nil {
		return x.RequestInfo
	}
	return nil
}

func (x *AddSubscriptionMessage_Request) GetSubscription() *UserSubscriptionMessage {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type AddSubscriptionMessage_Response struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ResponseInfo  *ResponseInfo            `protobuf:"bytes,1,opt,name=response_info,json=responseInfo,proto3" json:"response_info,omitempty"`
	Subscription  *UserSubscriptionMessage `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSubscriptionMessage_Response) Reset() {
	*x = AddSubscriptionMessage_Response{}
	mi := &file_proto_api_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSubscriptionMessage_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSubscriptionMessage_Response) ProtoMessage() {}

func (x *AddSubscriptionMessage_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSubscriptionMessage_Response.ProtoReflect.Descriptor instead.
func (*AddSubscriptionMessage_Response) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{11, 1}
}

func (x *AddSubscriptionMessage_Response) GetResponseInfo() *ResponseInfo {
	if x != nil {
		return x.ResponseInfo
	}
	return nil
}

func (x *AddSubscriptionMessage_Response) GetSubscription() *UserSubscriptionMessage {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type RemoveSubscriptionMessage_Request struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	RequestInfo   *RequestInfo             `protobuf:"bytes,1,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	Subscription  *UserSubscriptionMessage `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSubscriptionMessage_Request) Reset() {
	*x = RemoveSubscriptionMessage_Request{}
	mi := &file_proto_api_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSubscriptionMessage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubscriptionMessage_Request) ProtoMessage() {}

func (x *RemoveSubscriptionMessage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubscriptionMessage_Request.ProtoReflect.Descriptor instead.
func (*RemoveSubscriptionMessage_Request) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{12, 0}
}

func (x *RemoveSubscriptionMessage_Request) GetRequestInfo() *RequestInfo {
	if x != nil {
		return x.RequestInfo
	}
	return nil
}

func (x *RemoveSubscriptionMessage_Request) GetSubscription() *UserSubscriptionMessage {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type RemoveSubscriptionMessage_Response struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ResponseInfo  *ResponseInfo            `protobuf:"bytes,1,opt,name=response_info,json=responseInfo,proto3" json:"response_info,omitempty"`
	Subscription  *UserSubscriptionMessage `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSubscriptionMessage_Response) Reset() {
	*x = RemoveSubscriptionMessage_Response{}
	mi := &file_proto_api_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSubscriptionMessage_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubscriptionMessage_Response) ProtoMessage() {}

func (x *RemoveSubscriptionMessage_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubscriptionMessage_Response.ProtoReflect.Descriptor instead.
func (*RemoveSubscriptionMessage_Response) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{12, 1}
}

func (x *RemoveSubscriptionMessage_Response) GetResponseInfo() *ResponseInfo {
	if x != nil {
		return x.ResponseInfo
	}
	return nil
}

func (x *RemoveSubscriptionMessage_Response) GetSubscription() *UserSubscriptionMessage {
	if x != nil {
		return x.Subscription
	}
	return nil
}

var File_proto_api_proto protoreflect.FileDescriptor

const file_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/api.proto\x12\fresonate.api\x1a\x12proto/common.proto\"M\n" +
	"\fResponseInfo\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"I\n" +
	"\vRequestInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"\xfd\x02\n" +
	"\x12RefreshAuthMessage\x12B\n" +
	"\arequest\x18\x01 \x01(\v2(.resonate.api.RefreshAuthMessage.RequestR\arequest\x12E\n" +
	"\bresponse\x18\x02 \x01(\v2).resonate.api.RefreshAuthMessage.ResponseR\bresponse\x1al\n" +
	"\aRequest\x12<\n" +
	"\frequest_info\x18\x01 \x01(\v2\x19.resonate.api.RequestInfoR\vrequestInfo\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x1an\n" +
	"\bResponse\x12?\n" +
	"\rresponse_info\x18\x01 \x01(\v2\x1a.resonate.api.ResponseInfoR\fresponseInfo\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"\xce\x02\n" +
	"\x13LoginRequestMessage\x12C\n" +
	"\arequest\x18\x01 \x01(\v2).resonate.api.LoginRequestMessage.RequestR\arequest\x12F\n" +
	"\bresponse\x18\x02 \x01(\v2*.resonate.api.LoginRequestMessage.ResponseR\bresponse\x1a]\n" +
	"\aRequest\x12<\n" +
	"\frequest_info\x18\x01 \x01(\v2\x19.resonate.api.RequestInfoR\vrequestInfo\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x1aK\n" +
	"\bResponse\x12?\n" +
	"\rresponse_info\x18\x01 \x01(\v2\x1a.resonate.api.ResponseInfoR\fresponseInfo\"\xd5\x03\n" +
	"\x10LoginUserMessage\x12@\n" +
	"\arequest\x18\x01 \x01(\v2&.resonate.api.LoginUserMessage.RequestR\arequest\x12C\n" +
	"\bresponse\x18\x02 \x01(\v2'.resonate.api.LoginUserMessage.ResponseR\bresponse\x1ay\n" +
	"\aRequest\x12<\n" +
	"\frequest_info\x18\x01 \x01(\v2\x19.resonate.api.RequestInfoR\vrequestInfo\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x1a\xbe\x01\n" +
	"\bResponse\x12?\n" +
	"\rresponse_info\x18\x01 \x01(\v2\x1a.resonate.api.ResponseInfoR\fresponseInfo\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12)\n" +
	"\x04user\x18\x04 \x01(\v2\x15.resonate.UserMessageR\x04user\"\x88\x03\n" +
	"\x11CreateUserMessage\x12A\n" +
	"\arequest\x18\x01 \x01(\v2'.resonate.api.CreateUserMessage.RequestR\arequest\x12D\n" +
	"\bresponse\x18\x02 \x01(\v2(.resonate.api.CreateUserMessage.ResponseR\bresponse\x1ar\n" +
	"\aRequest\x12<\n" +
	"\frequest_info\x18\x01 \x01(\v2\x19.resonate.api.RequestInfoR\vrequestInfo\x12)\n" +
	"\x04user\x18\x02 \x01(\v2\x15.resonate.UserMessageR\x04user\x1av\n" +
	"\bResponse\x12?\n" +
	"\rresponse_info\x18\x01 \x01(\v2\x1a.resonate.api.ResponseInfoR\fresponseInfo\x12)\n" +
	"\x04user\x18\x02 \x01(\v2\x15.resonate.UserMessageR\x04user\"\xed\x02\n" +
	"\x0eGetUserMessage\x12>\n" +
	"\arequest\x18\x01 \x01(\v2$.resonate.api.GetUserMessage.RequestR\arequest\x12A\n" +
	"\bresponse\x18\x02 \x01(\v2%.resonate.api.GetUserMessage.ResponseR\bresponse\x1a`\n" +
	"\aRequest\x12<\n" +
	"\frequest_info\x18\x01 \x01(\v2\x19.resonate.api.RequestInfoR\vrequestInfo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x1av\n" +
	"\bResponse\x12?\n" +
	"\rresponse_info\x18\x01 \x01(\v2\x1a.resonate.api.ResponseInfoR\fresponseInfo\x12)\n" +
	"\x04user\x18\x02 \x01(\v2\x15.resonate.UserMessageR\x04user\"\x88\x03\n" +
	"\x11UpdateUserMessage\x12A\n" +
	"\arequest\x18\x01 \x01(\v2'.resonate.api.UpdateUserMessage.RequestR\arequest\x12D\n" +
	"\bresponse\x18\x02 \x01(\v2(.resonate.api.UpdateUserMessage.ResponseR\bresponse\x1ar\n" +
	"\aRequest\x12<\n" +
	"\frequest_info\x18\x01 \x01(\v2\x19.resonate.api.RequestInfoR\vrequestInfo\x12)\n" +
	"\x04user\x18\x02 \x01(\v2\x15.resonate.UserMessageR\x04user\x1av\n" +
	"\bResponse\x12?\n" +
	"\rresponse_info\x18\x01 \x01(\v2\x1a.resonate.api.ResponseInfoR\fresponseInfo\x12)\n" +
	"\x04user\x18\x02 \x01(\v2\x15.resonate.UserMessageR\x04user\"\xd6\x03\n" +
	"\rSearchMessage\x12=\n" +
	"\arequest\x18\x01 \x01(\v2#.resonate.api.SearchMessage.RequestR\arequest\x12@\n" +
	"\bresponse\x18\x02 \x01(\v2$.resonate.api.SearchMessage.ResponseR\bresponse\x1a]\n" +
	"\aRequest\x12<\n" +
	"\frequest_info\x18\x01 \x01(\v2\x19.resonate.api.RequestInfoR\vrequestInfo\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x1a\xe4\x01\n" +
	"\bResponse\x12?\n" +
	"\rresponse_info\x18\x01 \x01(\v2\x1a.resonate.api.ResponseInfoR\fresponseInfo\x124\n" +
	"\bpodcasts\x18\x02 \x03(\v2\x18.resonate.PodcastMessageR\bpodcasts\x12+\n" +
	"\x05users\x18\x03 \x03(\v2\x15.resonate.UserMessageR\x05users\x124\n" +
	"\bepisodes\x18\x04 \x03(\v2\x18.resonate.EpisodeMessageR\bepisodes\"\x85\x03\n" +
	"\x11GetPodcastMessage\x12A\n" +
	"\arequest\x18\x01 \x01(\v2'.resonate.api.GetPodcastMessage.RequestR\arequest\x12D\n" +
	"\bresponse\x18\x02 \x01(\v2(.resonate.api.GetPodcastMessage.ResponseR\bresponse\x1af\n" +
	"\aRequest\x12<\n" +
	"\frequest_info\x18\x01 \x01(\v2\x19.resonate.api.RequestInfoR\vrequestInfo\x12\x1d\n" +
	"\n" +
	"podcast_id\x18\x02 \x01(\tR\tpodcastId\x1a\x7f\n" +
	"\bResponse\x12?\n" +
	"\rresponse_info\x18\x01 \x01(\v2\x1a.resonate.api.ResponseInfoR\fresponseInfo\x122\n" +
	"\apodcast\x18\x02 \x01(\v2\x18.resonate.PodcastMessageR\apodcast\"\x85\x03\n" +
	"\x11GetEpisodeMessage\x12A\n" +
	"\arequest\x18\x01 \x01(\v2'.resonate.api.GetEpisodeMessage.RequestR\arequest\x12D\n" +
	"\bresponse\x18\x02 \x01(\v2(.resonate.api.GetEpisodeMessage.ResponseR\bresponse\x1af\n" +
	"\aRequest\x12<\n" +
	"\frequest_info\x18\x01 \x01(\v2\x19.resonate.api.RequestInfoR\vrequestInfo\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x02 \x01(\tR\tepisodeId\x1a\x7f\n" +
	"\bResponse\x12?\n" +
	"\rresponse_info\x18\x01 \x01(\v2\x1a.resonate.api.ResponseInfoR\fresponseInfo\x122\n" +
	"\aepisode\x18\x02 \x01(\v2\x18.resonate.EpisodeMessageR\aepisode\"\xd1\x03\n" +
	"\x16AddSubscriptionMessage\x12F\n" +
	"\arequest\x18\x01 \x01(\v2,.resonate.api.AddSubscriptionMessage.RequestR\arequest\x12I\n" +
	"\bresponse\x18\x02 \x01(\v2-.resonate.api.AddSubscriptionMessage.ResponseR\bresponse\x1a\x8e\x01\n" +
	"\aRequest\x12<\n" +
	"\frequest_info\x18\x01 \x01(\v2\x19.resonate.api.RequestInfoR\vrequestInfo\x12E\n" +
	"\fsubscription\x18\x02 \x01(\v2!.resonate.UserSubscriptionMessageR\fsubscription\x1a\x92\x01\n" +
	"\bResponse\x12?\n" +
	"\rresponse_info\x18\x01 \x01(\v2\x1a.resonate.api.ResponseInfoR\fresponseInfo\x12E\n" +
	"\fsubscription\x18\x02 \x01(\v2!.resonate.UserSubscriptionMessageR\fsubscription\"\xda\x03\n" +
	"\x19RemoveSubscriptionMessage\x12I\n" +
	"\arequest\x18\x01 \x01(\v2/.resonate.api.RemoveSubscriptionMessage.RequestR\arequest\x12L\n" +
	"\bresponse\x18\x02 \x01(\v20.resonate.api.RemoveSubscriptionMessage.ResponseR\bresponse\x1a\x8e\x01\n" +
	"\aRequest\x12<\n" +
	"\frequest_info\x18\x01 \x01(\v2\x19.resonate.api.RequestInfoR\vrequestInfo\x12E\n" +
	"\fsubscription\x18\x02 \x01(\v2!.resonate.UserSubscriptionMessageR\fsubscription\x1a\x92\x01\n" +
	"\bResponse\x12?\n" +
	"\rresponse_info\x18\x01 \x01(\v2\x1a.resonate.api.ResponseInfoR\fresponseInfo\x12E\n" +
	"\fsubscription\x18\x02 \x01(\v2!.resonate.UserSubscriptionMessageR\fsubscriptionB#Z!github.com/dghwood/resonate/protob\x06proto3"

var (
	file_proto_api_proto_rawDescOnce sync.Once
	file_proto_api_proto_rawDescData []byte
)

func file_proto_api_proto_rawDescGZIP() []byte {
	file_proto_api_proto_rawDescOnce.Do(func() {
		file_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)))
	})
	return file_proto_api_proto_rawDescData
}

var file_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_api_proto_goTypes = []any{
	(*ResponseInfo)(nil),                       // 0: resonate.api.ResponseInfo
	(*RequestInfo)(nil),                        // 1: resonate.api.RequestInfo
	(*RefreshAuthMessage)(nil),                 // 2: resonate.api.RefreshAuthMessage
	(*LoginRequestMessage)(nil),                // 3: resonate.api.LoginRequestMessage
	(*LoginUserMessage)(nil),                   // 4: resonate.api.LoginUserMessage
	(*CreateUserMessage)(nil),                  // 5: resonate.api.CreateUserMessage
	(*GetUserMessage)(nil),                     // 6: resonate.api.GetUserMessage
	(*UpdateUserMessage)(nil),                  // 7: resonate.api.UpdateUserMessage
	(*SearchMessage)(nil),                      // 8: resonate.api.SearchMessage
	(*GetPodcastMessage)(nil),                  // 9: resonate.api.GetPodcastMessage
	(*GetEpisodeMessage)(nil),                  // 10: resonate.api.GetEpisodeMessage
	(*AddSubscriptionMessage)(nil),             // 11: resonate.api.AddSubscriptionMessage
	(*RemoveSubscriptionMessage)(nil),          // 12: resonate.api.RemoveSubscriptionMessage
	(*RefreshAuthMessage_Request)(nil),         // 13: resonate.api.RefreshAuthMessage.Request
	(*RefreshAuthMessage_Response)(nil),        // 14: resonate.api.RefreshAuthMessage.Response
	(*LoginRequestMessage_Request)(nil),        // 15: resonate.api.LoginRequestMessage.Request
	(*LoginRequestMessage_Response)(nil),       // 16: resonate.api.LoginRequestMessage.Response
	(*LoginUserMessage_Request)(nil),           // 17: resonate.api.LoginUserMessage.Request
	(*LoginUserMessage_Response)(nil),          // 18: resonate.api.LoginUserMessage.Response
	(*CreateUserMessage_Request)(nil),          // 19: resonate.api.CreateUserMessage.Request
	(*CreateUserMessage_Response)(nil),         // 20: resonate.api.CreateUserMessage.Response
	(*GetUserMessage_Request)(nil),             // 21: resonate.api.GetUserMessage.Request
	(*GetUserMessage_Response)(nil),            // 22: resonate.api.GetUserMessage.Response
	(*UpdateUserMessage_Request)(nil),          // 23: resonate.api.UpdateUserMessage.Request
	(*UpdateUserMessage_Response)(nil),         // 24: resonate.api.UpdateUserMessage.Response
	(*SearchMessage_Request)(nil),              // 25: resonate.api.SearchMessage.Request
	(*SearchMessage_Response)(nil),             // 26: resonate.api.SearchMessage.Response
	(*GetPodcastMessage_Request)(nil),          // 27: resonate.api.GetPodcastMessage.Request
	(*GetPodcastMessage_Response)(nil),         // 28: resonate.api.GetPodcastMessage.Response
	(*GetEpisodeMessage_Request)(nil),          // 29: resonate.api.GetEpisodeMessage.Request
	(*GetEpisodeMessage_Response)(nil),         // 30: resonate.api.GetEpisodeMessage.Response
	(*AddSubscriptionMessage_Request)(nil),     // 31: resonate.api.AddSubscriptionMessage.Request
	(*AddSubscriptionMessage_Response)(nil),    // 32: resonate.api.AddSubscriptionMessage.Response
	(*RemoveSubscriptionMessage_Request)(nil),  // 33: resonate.api.RemoveSubscriptionMessage.Request
	(*RemoveSubscriptionMessage_Response)(nil), // 34: resonate.api.RemoveSubscriptionMessage.Response
	(*UserMessage)(nil),                        // 35: resonate.UserMessage
	(*PodcastMessage)(nil),                     // 36: resonate.PodcastMessage
	(*EpisodeMessage)(nil),                     // 37: resonate.EpisodeMessage
	(*UserSubscriptionMessage)(nil),            // 38: resonate.UserSubscriptionMessage
}
var file_proto_api_proto_depIdxs = []int32{
	13, // 0: resonate.api.RefreshAuthMessage.request:type_name -> resonate.api.RefreshAuthMessage.Request
	14, // 1: resonate.api.RefreshAuthMessage.response:type_name -> resonate.api.RefreshAuthMessage.Response
	15, // 2: resonate.api.LoginRequestMessage.request:type_name -> resonate.api.LoginRequestMessage.Request
	16, // 3: resonate.api.LoginRequestMessage.response:type_name -> resonate.api.LoginRequestMessage.Response
	17, // 4: resonate.api.LoginUserMessage.request:type_name -> resonate.api.LoginUserMessage.Request
	18, // 5: resonate.api.LoginUserMessage.response:type_name -> resonate.api.LoginUserMessage.Response
	19, // 6: resonate.api.CreateUserMessage.request:type_name -> resonate.api.CreateUserMessage.Request
	20, // 7: resonate.api.CreateUserMessage.response:type_name -> resonate.api.CreateUserMessage.Response
	21, // 8: resonate.api.GetUserMessage.request:type_name -> resonate.api.GetUserMessage.Request
	22, // 9: resonate.api.GetUserMessage.response:type_name -> resonate.api.GetUserMessage.Response
	23, // 10: resonate.api.UpdateUserMessage.request:type_name -> resonate.api.UpdateUserMessage.Request
	24, // 11: resonate.api.UpdateUserMessage.response:type_name -> resonate.api.UpdateUserMessage.Response
	25, // 12: resonate.api.SearchMessage.request:type_name -> resonate.api.SearchMessage.Request
	26, // 13: resonate.api.SearchMessage.response:type_name -> resonate.api.SearchMessage.Response
	27, // 14: resonate.api.GetPodcastMessage.request:type_name -> resonate.api.GetPodcastMessage.Request
	28, // 15: resonate.api.GetPodcastMessage.response:type_name -> resonate.api.GetPodcastMessage.Response
	29, // 16: resonate.api.GetEpisodeMessage.request:type_name -> resonate.api.GetEpisodeMessage.Request
	30, // 17: resonate.api.GetEpisodeMessage.response:type_name -> resonate.api.GetEpisodeMessage.Response
	31, // 18: resonate.api.AddSubscriptionMessage.request:type_name -> resonate.api.AddSubscriptionMessage.Request
	32, // 19: resonate.api.AddSubscriptionMessage.response:type_name -> resonate.api.AddSubscriptionMessage.Response
	33, // 20: resonate.api.RemoveSubscriptionMessage.request:type_name -> resonate.api.RemoveSubscriptionMessage.Request
	34, // 21: resonate.api.RemoveSubscriptionMessage.response:type_name -> resonate.api.RemoveSubscriptionMessage.Response
	1,  // 22: resonate.api.RefreshAuthMessage.Request.request_info:type_name -> resonate.api.RequestInfo
	0,  // 23: resonate.api.RefreshAuthMessage.Response.response_info:type_name -> resonate.api.ResponseInfo
	1,  // 24: resonate.api.LoginRequestMessage.Request.request_info:type_name -> resonate.api.RequestInfo
	0,  // 25: resonate.api.LoginRequestMessage.Response.response_info:type_name -> resonate.api.ResponseInfo
	1,  // 26: resonate.api.LoginUserMessage.Request.request_info:type_name -> resonate.api.RequestInfo
	0,  // 27: resonate.api.LoginUserMessage.Response.response_info:type_name -> resonate.api.ResponseInfo
	35, // 28: resonate.api.LoginUserMessage.Response.user:type_name -> resonate.UserMessage
	1,  // 29: resonate.api.CreateUserMessage.Request.request_info:type_name -> resonate.api.RequestInfo
	35, // 30: resonate.api.CreateUserMessage.Request.user:type_name -> resonate.UserMessage
	0,  // 31: resonate.api.CreateUserMessage.Response.response_info:type_name -> resonate.api.ResponseInfo
	35, // 32: resonate.api.CreateUserMessage.Response.user:type_name -> resonate.UserMessage
	1,  // 33: resonate.api.GetUserMessage.Request.request_info:type_name -> resonate.api.RequestInfo
	0,  // 34: resonate.api.GetUserMessage.Response.response_info:type_name -> resonate.api.ResponseInfo
	35, // 35: resonate.api.GetUserMessage.Response.user:type_name -> resonate.UserMessage
	1,  // 36: resonate.api.UpdateUserMessage.Request.request_info:type_name -> resonate.api.RequestInfo
	35, // 37: resonate.api.UpdateUserMessage.Request.user:type_name -> resonate.UserMessage
	0,  // 38: resonate.api.UpdateUserMessage.Response.response_info:type_name -> resonate.api.ResponseInfo
	35, // 39: resonate.api.UpdateUserMessage.Response.user:type_name -> resonate.UserMessage
	1,  // 40: resonate.api.SearchMessage.Request.request_info:type_name -> resonate.api.RequestInfo
	0,  // 41: resonate.api.SearchMessage.Response.response_info:type_name -> resonate.api.ResponseInfo
	36, // 42: resonate.api.SearchMessage.Response.podcasts:type_name -> resonate.PodcastMessage
	35, // 43: resonate.api.SearchMessage.Response.users:type_name -> resonate.UserMessage
	37, // 44: resonate.api.SearchMessage.Response.episodes:type_name -> resonate.EpisodeMessage
	1,  // 45: resonate.api.GetPodcastMessage.Request.request_info:type_name -> resonate.api.RequestInfo
	0,  // 46: resonate.api.GetPodcastMessage.Response.response_info:type_name -> resonate.api.ResponseInfo
	36, // 47: resonate.api.GetPodcastMessage.Response.podcast:type_name -> resonate.PodcastMessage
	1,  // 48: resonate.api.GetEpisodeMessage.Request.request_info:type_name -> resonate.api.RequestInfo
	0,  // 49: resonate.api.GetEpisodeMessage.Response.response_info:type_name -> resonate.api.ResponseInfo
	37, // 50: resonate.api.GetEpisodeMessage.Response.episode:type_name -> resonate.EpisodeMessage
	1,  // 51: resonate.api.AddSubscriptionMessage.Request.request_info:type_name -> resonate.api.RequestInfo
	38, // 52: resonate.api.AddSubscriptionMessage.Request.subscription:type_name -> resonate.UserSubscriptionMessage
	0,  // 53: resonate.api.AddSubscriptionMessage.Response.response_info:type_name -> resonate.api.ResponseInfo
	38, // 54: resonate.api.AddSubscriptionMessage.Response.subscription:type_name -> resonate.UserSubscriptionMessage
	1,  // 55: resonate.api.RemoveSubscriptionMessage.Request.request_info:type_name -> resonate.api.RequestInfo
	38, // 56: resonate.api.RemoveSubscriptionMessage.Request.subscription:type_name -> resonate.UserSubscriptionMessage
	0,  // 57: resonate.api.RemoveSubscriptionMessage.Response.response_info:type_name -> resonate.api.ResponseInfo
	38, // 58: resonate.api.RemoveSubscriptionMessage.Response.subscription:type_name -> resonate.UserSubscriptionMessage
	59, // [59:59] is the sub-list for method output_type
	59, // [59:59] is the sub-list for method input_type
	59, // [59:59] is the sub-list for extension type_name
	59, // [59:59] is the sub-list for extension extendee
	0,  // [0:59] is the sub-list for field type_name
}

func init() { file_proto_api_proto_init() }
func file_proto_api_proto_init() {
	if File_proto_api_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_proto_goTypes,
		DependencyIndexes: file_proto_api_proto_depIdxs,
		MessageInfos:      file_proto_api_proto_msgTypes,
	}.Build()
	File_proto_api_proto = out.File
	file_proto_api_proto_goTypes = nil
	file_proto_api_proto_depIdxs = nil
}
