// Common Resonate Protos
//
// Create User
// Search Podcasts
// Show podcast details & episodes
// Subscribe to podcast
// Show subscription list
// Subscribed episodes show up in feed
// Listen to episodes
// Log episodes as listened
// Search for users
// Show listened episodes & subscriptions
// Follow users

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodcastMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Url         string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	ImageUrl    string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Author      string                 `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	// this is optional
	Episodes      []*EpisodeMessage `protobuf:"bytes,7,rep,name=episodes,proto3" json:"episodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodcastMessage) Reset() {
	*x = PodcastMessage{}
	mi := &file_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodcastMessage) ProtoMessage() {}

func (x *PodcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodcastMessage.ProtoReflect.Descriptor instead.
func (*PodcastMessage) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *PodcastMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PodcastMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PodcastMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PodcastMessage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PodcastMessage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *PodcastMessage) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PodcastMessage) GetEpisodes() []*EpisodeMessage {
	if x != nil {
		return x.Episodes
	}
	return nil
}

type EpisodeMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PodcastId        string                 `protobuf:"bytes,2,opt,name=podcast_id,json=podcastId,proto3" json:"podcast_id,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AudioUrl         string                 `protobuf:"bytes,5,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	PublishTimestamp int64                  `protobuf:"varint,8,opt,name=publish_timestamp,json=publishTimestamp,proto3" json:"publish_timestamp,omitempty"`
	DurationSeconds  int64                  `protobuf:"varint,9,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	EpisodeNumber    int64                  `protobuf:"varint,10,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	Explicit         bool                   `protobuf:"varint,11,opt,name=explicit,proto3" json:"explicit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EpisodeMessage) Reset() {
	*x = EpisodeMessage{}
	mi := &file_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeMessage) ProtoMessage() {}

func (x *EpisodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeMessage.ProtoReflect.Descriptor instead.
func (*EpisodeMessage) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *EpisodeMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EpisodeMessage) GetPodcastId() string {
	if x != nil {
		return x.PodcastId
	}
	return ""
}

func (x *EpisodeMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EpisodeMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EpisodeMessage) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

func (x *EpisodeMessage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *EpisodeMessage) GetPublishTimestamp() int64 {
	if x != nil {
		return x.PublishTimestamp
	}
	return 0
}

func (x *EpisodeMessage) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *EpisodeMessage) GetEpisodeNumber() int64 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *EpisodeMessage) GetExplicit() bool {
	if x != nil {
		return x.Explicit
	}
	return false
}

type UserMessage struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Id            string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ImageUrl      string                     `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Subscriptions []*UserSubscriptionMessage `protobuf:"bytes,5,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Listens       []*UserListenMessage       `protobuf:"bytes,6,rep,name=listens,proto3" json:"listens,omitempty"`
	Following     []*UserFollowMessage       `protobuf:"bytes,7,rep,name=following,proto3" json:"following,omitempty"`
	NumFollowers  int64                      `protobuf:"varint,8,opt,name=num_followers,json=numFollowers,proto3" json:"num_followers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *UserMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserMessage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UserMessage) GetSubscriptions() []*UserSubscriptionMessage {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *UserMessage) GetListens() []*UserListenMessage {
	if x != nil {
		return x.Listens
	}
	return nil
}

func (x *UserMessage) GetFollowing() []*UserFollowMessage {
	if x != nil {
		return x.Following
	}
	return nil
}

func (x *UserMessage) GetNumFollowers() int64 {
	if x != nil {
		return x.NumFollowers
	}
	return 0
}

type UserFollowMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowedUserId string                 `protobuf:"bytes,2,opt,name=followed_user_id,json=followedUserId,proto3" json:"followed_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserFollowMessage) Reset() {
	*x = UserFollowMessage{}
	mi := &file_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFollowMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFollowMessage) ProtoMessage() {}

func (x *UserFollowMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFollowMessage.ProtoReflect.Descriptor instead.
func (*UserFollowMessage) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *UserFollowMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserFollowMessage) GetFollowedUserId() string {
	if x != nil {
		return x.FollowedUserId
	}
	return ""
}

type UserSubscriptionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PodcastId     string                 `protobuf:"bytes,2,opt,name=podcast_id,json=podcastId,proto3" json:"podcast_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSubscriptionMessage) Reset() {
	*x = UserSubscriptionMessage{}
	mi := &file_proto_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSubscriptionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSubscriptionMessage) ProtoMessage() {}

func (x *UserSubscriptionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSubscriptionMessage.ProtoReflect.Descriptor instead.
func (*UserSubscriptionMessage) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{4}
}

func (x *UserSubscriptionMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSubscriptionMessage) GetPodcastId() string {
	if x != nil {
		return x.PodcastId
	}
	return ""
}

type UserListenMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EpisodeId       string                 `protobuf:"bytes,2,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	ListenTimestamp int64                  `protobuf:"varint,3,opt,name=listen_timestamp,json=listenTimestamp,proto3" json:"listen_timestamp,omitempty"`
	Seconds         int64                  `protobuf:"varint,4,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Completed       bool                   `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"`
	Episode         *EpisodeMessage        `protobuf:"bytes,6,opt,name=episode,proto3" json:"episode,omitempty"` // this is optional, used for feed items
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserListenMessage) Reset() {
	*x = UserListenMessage{}
	mi := &file_proto_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListenMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListenMessage) ProtoMessage() {}

func (x *UserListenMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListenMessage.ProtoReflect.Descriptor instead.
func (*UserListenMessage) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{5}
}

func (x *UserListenMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserListenMessage) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *UserListenMessage) GetListenTimestamp() int64 {
	if x != nil {
		return x.ListenTimestamp
	}
	return 0
}

func (x *UserListenMessage) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *UserListenMessage) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *UserListenMessage) GetEpisode() *EpisodeMessage {
	if x != nil {
		return x.Episode
	}
	return nil
}

type UserFeedItemMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Episode       *EpisodeMessage        `protobuf:"bytes,1,opt,name=episode,proto3" json:"episode,omitempty"`
	Listen        *UserListenMessage     `protobuf:"bytes,2,opt,name=listen,proto3" json:"listen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFeedItemMessage) Reset() {
	*x = UserFeedItemMessage{}
	mi := &file_proto_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFeedItemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFeedItemMessage) ProtoMessage() {}

func (x *UserFeedItemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFeedItemMessage.ProtoReflect.Descriptor instead.
func (*UserFeedItemMessage) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{6}
}

func (x *UserFeedItemMessage) GetEpisode() *EpisodeMessage {
	if x != nil {
		return x.Episode
	}
	return nil
}

func (x *UserFeedItemMessage) GetListen() *UserListenMessage {
	if x != nil {
		return x.Listen
	}
	return nil
}

type UserFeedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*UserFeedItemMessage `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFeedMessage) Reset() {
	*x = UserFeedMessage{}
	mi := &file_proto_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFeedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFeedMessage) ProtoMessage() {}

func (x *UserFeedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFeedMessage.ProtoReflect.Descriptor instead.
func (*UserFeedMessage) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{7}
}

func (x *UserFeedMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserFeedMessage) GetItems() []*UserFeedItemMessage {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_common_proto protoreflect.FileDescriptor

const file_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x12proto/common.proto\x12\bresonate\"\xd5\x01\n" +
	"\x0ePodcastMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x16\n" +
	"\x06author\x18\x06 \x01(\tR\x06author\x124\n" +
	"\bepisodes\x18\a \x03(\v2\x18.resonate.EpisodeMessageR\bepisodes\"\xcc\x02\n" +
	"\x0eEpisodeMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"podcast_id\x18\x02 \x01(\tR\tpodcastId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\taudio_url\x18\x05 \x01(\tR\baudioUrl\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12+\n" +
	"\x11publish_timestamp\x18\b \x01(\x03R\x10publishTimestamp\x12)\n" +
	"\x10duration_seconds\x18\t \x01(\x03R\x0fdurationSeconds\x12%\n" +
	"\x0eepisode_number\x18\n" +
	" \x01(\x03R\repisodeNumber\x12\x1a\n" +
	"\bexplicit\x18\v \x01(\bR\bexplicit\"\xc4\x02\n" +
	"\vUserMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12G\n" +
	"\rsubscriptions\x18\x05 \x03(\v2!.resonate.UserSubscriptionMessageR\rsubscriptions\x125\n" +
	"\alistens\x18\x06 \x03(\v2\x1b.resonate.UserListenMessageR\alistens\x129\n" +
	"\tfollowing\x18\a \x03(\v2\x1b.resonate.UserFollowMessageR\tfollowing\x12#\n" +
	"\rnum_followers\x18\b \x01(\x03R\fnumFollowers\"V\n" +
	"\x11UserFollowMessage\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x10followed_user_id\x18\x02 \x01(\tR\x0efollowedUserId\"Q\n" +
	"\x17UserSubscriptionMessage\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"podcast_id\x18\x02 \x01(\tR\tpodcastId\"\xe2\x01\n" +
	"\x11UserListenMessage\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x02 \x01(\tR\tepisodeId\x12)\n" +
	"\x10listen_timestamp\x18\x03 \x01(\x03R\x0flistenTimestamp\x12\x18\n" +
	"\aseconds\x18\x04 \x01(\x03R\aseconds\x12\x1c\n" +
	"\tcompleted\x18\x05 \x01(\bR\tcompleted\x122\n" +
	"\aepisode\x18\x06 \x01(\v2\x18.resonate.EpisodeMessageR\aepisode\"~\n" +
	"\x13UserFeedItemMessage\x122\n" +
	"\aepisode\x18\x01 \x01(\v2\x18.resonate.EpisodeMessageR\aepisode\x123\n" +
	"\x06listen\x18\x02 \x01(\v2\x1b.resonate.UserListenMessageR\x06listen\"_\n" +
	"\x0fUserFeedMessage\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x123\n" +
	"\x05items\x18\x02 \x03(\v2\x1d.resonate.UserFeedItemMessageR\x05itemsB#Z!github.com/dghwood/resonate/protob\x06proto3"

var (
	file_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_rawDescData []byte
)

func file_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)))
	})
	return file_proto_common_proto_rawDescData
}

var file_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_common_proto_goTypes = []any{
	(*PodcastMessage)(nil),          // 0: resonate.PodcastMessage
	(*EpisodeMessage)(nil),          // 1: resonate.EpisodeMessage
	(*UserMessage)(nil),             // 2: resonate.UserMessage
	(*UserFollowMessage)(nil),       // 3: resonate.UserFollowMessage
	(*UserSubscriptionMessage)(nil), // 4: resonate.UserSubscriptionMessage
	(*UserListenMessage)(nil),       // 5: resonate.UserListenMessage
	(*UserFeedItemMessage)(nil),     // 6: resonate.UserFeedItemMessage
	(*UserFeedMessage)(nil),         // 7: resonate.UserFeedMessage
}
var file_proto_common_proto_depIdxs = []int32{
	1, // 0: resonate.PodcastMessage.episodes:type_name -> resonate.EpisodeMessage
	4, // 1: resonate.UserMessage.subscriptions:type_name -> resonate.UserSubscriptionMessage
	5, // 2: resonate.UserMessage.listens:type_name -> resonate.UserListenMessage
	3, // 3: resonate.UserMessage.following:type_name -> resonate.UserFollowMessage
	1, // 4: resonate.UserListenMessage.episode:type_name -> resonate.EpisodeMessage
	1, // 5: resonate.UserFeedItemMessage.episode:type_name -> resonate.EpisodeMessage
	5, // 6: resonate.UserFeedItemMessage.listen:type_name -> resonate.UserListenMessage
	6, // 7: resonate.UserFeedMessage.items:type_name -> resonate.UserFeedItemMessage
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		MessageInfos:      file_proto_common_proto_msgTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
