// Common Resonate Protos
//
// Create User
// Search Podcasts
// Show podcast details & episodes
// Subscribe to podcast
// Show subscription list
// Subscribed episodes show up in feed
// Listen to episodes
// Log episodes as listened
// Search for users
// Show listened episodes & subscriptions
// Follow users

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/common.proto

//go:build !protoopaque

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageMetadataMessage struct {
	state     protoimpl.MessageState `protogen:"hybrid.v1"`
	IsDeleted bool                   `protobuf:"varint,1,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	// In milliseconds since epoch, UTC time
	UpdatedTimestamp int64 `protobuf:"varint,2,opt,name=updated_timestamp,json=updatedTimestamp,proto3" json:"updated_timestamp,omitempty"`
	// In milliseconds since epoch, UTC time
	CreatedTimestamp int64 `protobuf:"varint,3,opt,name=created_timestamp,json=createdTimestamp,proto3" json:"created_timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StorageMetadataMessage) Reset() {
	*x = StorageMetadataMessage{}
	mi := &file_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageMetadataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageMetadataMessage) ProtoMessage() {}

func (x *StorageMetadataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StorageMetadataMessage) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *StorageMetadataMessage) GetUpdatedTimestamp() int64 {
	if x != nil {
		return x.UpdatedTimestamp
	}
	return 0
}

func (x *StorageMetadataMessage) GetCreatedTimestamp() int64 {
	if x != nil {
		return x.CreatedTimestamp
	}
	return 0
}

func (x *StorageMetadataMessage) SetIsDeleted(v bool) {
	x.IsDeleted = v
}

func (x *StorageMetadataMessage) SetUpdatedTimestamp(v int64) {
	x.UpdatedTimestamp = v
}

func (x *StorageMetadataMessage) SetCreatedTimestamp(v int64) {
	x.CreatedTimestamp = v
}

type StorageMetadataMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	IsDeleted bool
	// In milliseconds since epoch, UTC time
	UpdatedTimestamp int64
	// In milliseconds since epoch, UTC time
	CreatedTimestamp int64
}

func (b0 StorageMetadataMessage_builder) Build() *StorageMetadataMessage {
	m0 := &StorageMetadataMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.IsDeleted = b.IsDeleted
	x.UpdatedTimestamp = b.UpdatedTimestamp
	x.CreatedTimestamp = b.CreatedTimestamp
	return m0
}

type PodcastMessage struct {
	state       protoimpl.MessageState `protogen:"hybrid.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Url         string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	ImageUrl    string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Author      string                 `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	// this is optional
	Episodes []*EpisodeMessage       `protobuf:"bytes,7,rep,name=episodes,proto3" json:"episodes,omitempty"`
	Metadata *StorageMetadataMessage `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Used for most recent episode
	LatestEpisodeTimestamp int64 `protobuf:"varint,9,opt,name=latest_episode_timestamp,json=latestEpisodeTimestamp,proto3" json:"latest_episode_timestamp,omitempty"`
	// Used for last URL fetch
	LastFetchTimestamp int64 `protobuf:"varint,10,opt,name=last_fetch_timestamp,json=lastFetchTimestamp,proto3" json:"last_fetch_timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PodcastMessage) Reset() {
	*x = PodcastMessage{}
	mi := &file_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodcastMessage) ProtoMessage() {}

func (x *PodcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PodcastMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PodcastMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PodcastMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PodcastMessage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PodcastMessage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *PodcastMessage) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PodcastMessage) GetEpisodes() []*EpisodeMessage {
	if x != nil {
		return x.Episodes
	}
	return nil
}

func (x *PodcastMessage) GetMetadata() *StorageMetadataMessage {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PodcastMessage) GetLatestEpisodeTimestamp() int64 {
	if x != nil {
		return x.LatestEpisodeTimestamp
	}
	return 0
}

func (x *PodcastMessage) GetLastFetchTimestamp() int64 {
	if x != nil {
		return x.LastFetchTimestamp
	}
	return 0
}

func (x *PodcastMessage) SetId(v string) {
	x.Id = v
}

func (x *PodcastMessage) SetTitle(v string) {
	x.Title = v
}

func (x *PodcastMessage) SetDescription(v string) {
	x.Description = v
}

func (x *PodcastMessage) SetUrl(v string) {
	x.Url = v
}

func (x *PodcastMessage) SetImageUrl(v string) {
	x.ImageUrl = v
}

func (x *PodcastMessage) SetAuthor(v string) {
	x.Author = v
}

func (x *PodcastMessage) SetEpisodes(v []*EpisodeMessage) {
	x.Episodes = v
}

func (x *PodcastMessage) SetMetadata(v *StorageMetadataMessage) {
	x.Metadata = v
}

func (x *PodcastMessage) SetLatestEpisodeTimestamp(v int64) {
	x.LatestEpisodeTimestamp = v
}

func (x *PodcastMessage) SetLastFetchTimestamp(v int64) {
	x.LastFetchTimestamp = v
}

func (x *PodcastMessage) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *PodcastMessage) ClearMetadata() {
	x.Metadata = nil
}

type PodcastMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          string
	Title       string
	Description string
	Url         string
	ImageUrl    string
	Author      string
	// this is optional
	Episodes []*EpisodeMessage
	Metadata *StorageMetadataMessage
	// Used for most recent episode
	LatestEpisodeTimestamp int64
	// Used for last URL fetch
	LastFetchTimestamp int64
}

func (b0 PodcastMessage_builder) Build() *PodcastMessage {
	m0 := &PodcastMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Title = b.Title
	x.Description = b.Description
	x.Url = b.Url
	x.ImageUrl = b.ImageUrl
	x.Author = b.Author
	x.Episodes = b.Episodes
	x.Metadata = b.Metadata
	x.LatestEpisodeTimestamp = b.LatestEpisodeTimestamp
	x.LastFetchTimestamp = b.LastFetchTimestamp
	return m0
}

type EpisodeMessage struct {
	state            protoimpl.MessageState  `protogen:"hybrid.v1"`
	Id               string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PodcastId        string                  `protobuf:"bytes,2,opt,name=podcast_id,json=podcastId,proto3" json:"podcast_id,omitempty"`
	Title            string                  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AudioUrl         string                  `protobuf:"bytes,5,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	ImageUrl         string                  `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	PublishTimestamp int64                   `protobuf:"varint,8,opt,name=publish_timestamp,json=publishTimestamp,proto3" json:"publish_timestamp,omitempty"`
	DurationSeconds  int64                   `protobuf:"varint,9,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	EpisodeNumber    int64                   `protobuf:"varint,10,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	Explicit         bool                    `protobuf:"varint,11,opt,name=explicit,proto3" json:"explicit,omitempty"`
	Metadata         *StorageMetadataMessage `protobuf:"bytes,12,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EpisodeMessage) Reset() {
	*x = EpisodeMessage{}
	mi := &file_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeMessage) ProtoMessage() {}

func (x *EpisodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EpisodeMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EpisodeMessage) GetPodcastId() string {
	if x != nil {
		return x.PodcastId
	}
	return ""
}

func (x *EpisodeMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EpisodeMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EpisodeMessage) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

func (x *EpisodeMessage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *EpisodeMessage) GetPublishTimestamp() int64 {
	if x != nil {
		return x.PublishTimestamp
	}
	return 0
}

func (x *EpisodeMessage) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *EpisodeMessage) GetEpisodeNumber() int64 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *EpisodeMessage) GetExplicit() bool {
	if x != nil {
		return x.Explicit
	}
	return false
}

func (x *EpisodeMessage) GetMetadata() *StorageMetadataMessage {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EpisodeMessage) SetId(v string) {
	x.Id = v
}

func (x *EpisodeMessage) SetPodcastId(v string) {
	x.PodcastId = v
}

func (x *EpisodeMessage) SetTitle(v string) {
	x.Title = v
}

func (x *EpisodeMessage) SetDescription(v string) {
	x.Description = v
}

func (x *EpisodeMessage) SetAudioUrl(v string) {
	x.AudioUrl = v
}

func (x *EpisodeMessage) SetImageUrl(v string) {
	x.ImageUrl = v
}

func (x *EpisodeMessage) SetPublishTimestamp(v int64) {
	x.PublishTimestamp = v
}

func (x *EpisodeMessage) SetDurationSeconds(v int64) {
	x.DurationSeconds = v
}

func (x *EpisodeMessage) SetEpisodeNumber(v int64) {
	x.EpisodeNumber = v
}

func (x *EpisodeMessage) SetExplicit(v bool) {
	x.Explicit = v
}

func (x *EpisodeMessage) SetMetadata(v *StorageMetadataMessage) {
	x.Metadata = v
}

func (x *EpisodeMessage) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *EpisodeMessage) ClearMetadata() {
	x.Metadata = nil
}

type EpisodeMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id               string
	PodcastId        string
	Title            string
	Description      string
	AudioUrl         string
	ImageUrl         string
	PublishTimestamp int64
	DurationSeconds  int64
	EpisodeNumber    int64
	Explicit         bool
	Metadata         *StorageMetadataMessage
}

func (b0 EpisodeMessage_builder) Build() *EpisodeMessage {
	m0 := &EpisodeMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.PodcastId = b.PodcastId
	x.Title = b.Title
	x.Description = b.Description
	x.AudioUrl = b.AudioUrl
	x.ImageUrl = b.ImageUrl
	x.PublishTimestamp = b.PublishTimestamp
	x.DurationSeconds = b.DurationSeconds
	x.EpisodeNumber = b.EpisodeNumber
	x.Explicit = b.Explicit
	x.Metadata = b.Metadata
	return m0
}

type TokenMessage struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	Token string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// timestamp in seconds, UTC time
	ExpiryUtcTimestamp int64 `protobuf:"varint,2,opt,name=expiry_utc_timestamp,json=expiryUtcTimestamp,proto3" json:"expiry_utc_timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TokenMessage) Reset() {
	*x = TokenMessage{}
	mi := &file_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenMessage) ProtoMessage() {}

func (x *TokenMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TokenMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenMessage) GetExpiryUtcTimestamp() int64 {
	if x != nil {
		return x.ExpiryUtcTimestamp
	}
	return 0
}

func (x *TokenMessage) SetToken(v string) {
	x.Token = v
}

func (x *TokenMessage) SetExpiryUtcTimestamp(v int64) {
	x.ExpiryUtcTimestamp = v
}

type TokenMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token string
	// timestamp in seconds, UTC time
	ExpiryUtcTimestamp int64
}

func (b0 TokenMessage_builder) Build() *TokenMessage {
	m0 := &TokenMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Token = b.Token
	x.ExpiryUtcTimestamp = b.ExpiryUtcTimestamp
	return m0
}

type LoginAttempt struct {
	state              protoimpl.MessageState  `protogen:"hybrid.v1"`
	Id                 string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PhoneNumber        string                  `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Password           string                  `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Metadata           *StorageMetadataMessage `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ExpiryUtcTimestamp int64                   `protobuf:"varint,5,opt,name=expiry_utc_timestamp,json=expiryUtcTimestamp,proto3" json:"expiry_utc_timestamp,omitempty"`
	NumAttempts        int64                   `protobuf:"varint,6,opt,name=num_attempts,json=numAttempts,proto3" json:"num_attempts,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LoginAttempt) Reset() {
	*x = LoginAttempt{}
	mi := &file_proto_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAttempt) ProtoMessage() {}

func (x *LoginAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginAttempt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoginAttempt) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *LoginAttempt) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginAttempt) GetMetadata() *StorageMetadataMessage {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *LoginAttempt) GetExpiryUtcTimestamp() int64 {
	if x != nil {
		return x.ExpiryUtcTimestamp
	}
	return 0
}

func (x *LoginAttempt) GetNumAttempts() int64 {
	if x != nil {
		return x.NumAttempts
	}
	return 0
}

func (x *LoginAttempt) SetId(v string) {
	x.Id = v
}

func (x *LoginAttempt) SetPhoneNumber(v string) {
	x.PhoneNumber = v
}

func (x *LoginAttempt) SetPassword(v string) {
	x.Password = v
}

func (x *LoginAttempt) SetMetadata(v *StorageMetadataMessage) {
	x.Metadata = v
}

func (x *LoginAttempt) SetExpiryUtcTimestamp(v int64) {
	x.ExpiryUtcTimestamp = v
}

func (x *LoginAttempt) SetNumAttempts(v int64) {
	x.NumAttempts = v
}

func (x *LoginAttempt) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *LoginAttempt) ClearMetadata() {
	x.Metadata = nil
}

type LoginAttempt_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                 string
	PhoneNumber        string
	Password           string
	Metadata           *StorageMetadataMessage
	ExpiryUtcTimestamp int64
	NumAttempts        int64
}

func (b0 LoginAttempt_builder) Build() *LoginAttempt {
	m0 := &LoginAttempt{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.PhoneNumber = b.PhoneNumber
	x.Password = b.Password
	x.Metadata = b.Metadata
	x.ExpiryUtcTimestamp = b.ExpiryUtcTimestamp
	x.NumAttempts = b.NumAttempts
	return m0
}

type UserStorageMessage struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	User          *UserMessage           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken   *TokenMessage          `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  *TokenMessage          `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStorageMessage) Reset() {
	*x = UserStorageMessage{}
	mi := &file_proto_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStorageMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStorageMessage) ProtoMessage() {}

func (x *UserStorageMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserStorageMessage) GetUser() *UserMessage {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserStorageMessage) GetAccessToken() *TokenMessage {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *UserStorageMessage) GetRefreshToken() *TokenMessage {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

func (x *UserStorageMessage) SetUser(v *UserMessage) {
	x.User = v
}

func (x *UserStorageMessage) SetAccessToken(v *TokenMessage) {
	x.AccessToken = v
}

func (x *UserStorageMessage) SetRefreshToken(v *TokenMessage) {
	x.RefreshToken = v
}

func (x *UserStorageMessage) HasUser() bool {
	if x == nil {
		return false
	}
	return x.User != nil
}

func (x *UserStorageMessage) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return x.AccessToken != nil
}

func (x *UserStorageMessage) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return x.RefreshToken != nil
}

func (x *UserStorageMessage) ClearUser() {
	x.User = nil
}

func (x *UserStorageMessage) ClearAccessToken() {
	x.AccessToken = nil
}

func (x *UserStorageMessage) ClearRefreshToken() {
	x.RefreshToken = nil
}

type UserStorageMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User         *UserMessage
	AccessToken  *TokenMessage
	RefreshToken *TokenMessage
}

func (b0 UserStorageMessage_builder) Build() *UserStorageMessage {
	m0 := &UserStorageMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.User = b.User
	x.AccessToken = b.AccessToken
	x.RefreshToken = b.RefreshToken
	return m0
}

type RefreshTokensMessage struct {
	state         protoimpl.MessageState  `protogen:"hybrid.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tokens        []*TokenMessage         `protobuf:"bytes,3,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Metadata      *StorageMetadataMessage `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokensMessage) Reset() {
	*x = RefreshTokensMessage{}
	mi := &file_proto_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokensMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokensMessage) ProtoMessage() {}

func (x *RefreshTokensMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RefreshTokensMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RefreshTokensMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefreshTokensMessage) GetTokens() []*TokenMessage {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *RefreshTokensMessage) GetMetadata() *StorageMetadataMessage {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RefreshTokensMessage) SetId(v string) {
	x.Id = v
}

func (x *RefreshTokensMessage) SetUserId(v string) {
	x.UserId = v
}

func (x *RefreshTokensMessage) SetTokens(v []*TokenMessage) {
	x.Tokens = v
}

func (x *RefreshTokensMessage) SetMetadata(v *StorageMetadataMessage) {
	x.Metadata = v
}

func (x *RefreshTokensMessage) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *RefreshTokensMessage) ClearMetadata() {
	x.Metadata = nil
}

type RefreshTokensMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id       string
	UserId   string
	Tokens   []*TokenMessage
	Metadata *StorageMetadataMessage
}

func (b0 RefreshTokensMessage_builder) Build() *RefreshTokensMessage {
	m0 := &RefreshTokensMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.UserId = b.UserId
	x.Tokens = b.Tokens
	x.Metadata = b.Metadata
	return m0
}

type UserMessage struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// What about country code, etc.
	// TODO(duncan): Maybe I should just not store this?
	PhoneNumber          string `protobuf:"bytes,10,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	EncryptedPhoneNumber string `protobuf:"bytes,11,opt,name=encrypted_phone_number,json=encryptedPhoneNumber,proto3" json:"encrypted_phone_number,omitempty"`
	// Should this be a data url?
	ImageUrl      string                     `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Subscriptions []*UserSubscriptionMessage `protobuf:"bytes,5,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Listens       []*UserListenMessage       `protobuf:"bytes,6,rep,name=listens,proto3" json:"listens,omitempty"`
	Following     []*UserFollowMessage       `protobuf:"bytes,7,rep,name=following,proto3" json:"following,omitempty"`
	NumFollowers  int64                      `protobuf:"varint,8,opt,name=num_followers,json=numFollowers,proto3" json:"num_followers,omitempty"`
	Metadata      *StorageMetadataMessage    `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_proto_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserMessage) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserMessage) GetEncryptedPhoneNumber() string {
	if x != nil {
		return x.EncryptedPhoneNumber
	}
	return ""
}

func (x *UserMessage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UserMessage) GetSubscriptions() []*UserSubscriptionMessage {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *UserMessage) GetListens() []*UserListenMessage {
	if x != nil {
		return x.Listens
	}
	return nil
}

func (x *UserMessage) GetFollowing() []*UserFollowMessage {
	if x != nil {
		return x.Following
	}
	return nil
}

func (x *UserMessage) GetNumFollowers() int64 {
	if x != nil {
		return x.NumFollowers
	}
	return 0
}

func (x *UserMessage) GetMetadata() *StorageMetadataMessage {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserMessage) SetId(v string) {
	x.Id = v
}

func (x *UserMessage) SetName(v string) {
	x.Name = v
}

func (x *UserMessage) SetEmail(v string) {
	x.Email = v
}

func (x *UserMessage) SetPhoneNumber(v string) {
	x.PhoneNumber = v
}

func (x *UserMessage) SetEncryptedPhoneNumber(v string) {
	x.EncryptedPhoneNumber = v
}

func (x *UserMessage) SetImageUrl(v string) {
	x.ImageUrl = v
}

func (x *UserMessage) SetSubscriptions(v []*UserSubscriptionMessage) {
	x.Subscriptions = v
}

func (x *UserMessage) SetListens(v []*UserListenMessage) {
	x.Listens = v
}

func (x *UserMessage) SetFollowing(v []*UserFollowMessage) {
	x.Following = v
}

func (x *UserMessage) SetNumFollowers(v int64) {
	x.NumFollowers = v
}

func (x *UserMessage) SetMetadata(v *StorageMetadataMessage) {
	x.Metadata = v
}

func (x *UserMessage) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *UserMessage) ClearMetadata() {
	x.Metadata = nil
}

type UserMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id    string
	Name  string
	Email string
	// What about country code, etc.
	// TODO(duncan): Maybe I should just not store this?
	PhoneNumber          string
	EncryptedPhoneNumber string
	// Should this be a data url?
	ImageUrl      string
	Subscriptions []*UserSubscriptionMessage
	Listens       []*UserListenMessage
	Following     []*UserFollowMessage
	NumFollowers  int64
	Metadata      *StorageMetadataMessage
}

func (b0 UserMessage_builder) Build() *UserMessage {
	m0 := &UserMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	x.Email = b.Email
	x.PhoneNumber = b.PhoneNumber
	x.EncryptedPhoneNumber = b.EncryptedPhoneNumber
	x.ImageUrl = b.ImageUrl
	x.Subscriptions = b.Subscriptions
	x.Listens = b.Listens
	x.Following = b.Following
	x.NumFollowers = b.NumFollowers
	x.Metadata = b.Metadata
	return m0
}

// Stripped down UserMessage for more public consumption
// eg. listens
type PublicUserMessage struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicUserMessage) Reset() {
	*x = PublicUserMessage{}
	mi := &file_proto_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicUserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicUserMessage) ProtoMessage() {}

func (x *PublicUserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicUserMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicUserMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublicUserMessage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *PublicUserMessage) SetId(v string) {
	x.Id = v
}

func (x *PublicUserMessage) SetName(v string) {
	x.Name = v
}

func (x *PublicUserMessage) SetImageUrl(v string) {
	x.ImageUrl = v
}

type PublicUserMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id       string
	Name     string
	ImageUrl string
}

func (b0 PublicUserMessage_builder) Build() *PublicUserMessage {
	m0 := &PublicUserMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Name = b.Name
	x.ImageUrl = b.ImageUrl
	return m0
}

type UserFollowMessage struct {
	state                protoimpl.MessageState  `protogen:"hybrid.v1"`
	Id                   string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowedUserId       string                  `protobuf:"bytes,3,opt,name=followed_user_id,json=followedUserId,proto3" json:"followed_user_id,omitempty"`
	FollowUtcTimestampMs int64                   `protobuf:"varint,4,opt,name=follow_utc_timestamp_ms,json=followUtcTimestampMs,proto3" json:"follow_utc_timestamp_ms,omitempty"`
	Metadata             *StorageMetadataMessage `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	User                 *PublicUserMessage      `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"` // optional user
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserFollowMessage) Reset() {
	*x = UserFollowMessage{}
	mi := &file_proto_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFollowMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFollowMessage) ProtoMessage() {}

func (x *UserFollowMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserFollowMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserFollowMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserFollowMessage) GetFollowedUserId() string {
	if x != nil {
		return x.FollowedUserId
	}
	return ""
}

func (x *UserFollowMessage) GetFollowUtcTimestampMs() int64 {
	if x != nil {
		return x.FollowUtcTimestampMs
	}
	return 0
}

func (x *UserFollowMessage) GetMetadata() *StorageMetadataMessage {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserFollowMessage) GetUser() *PublicUserMessage {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserFollowMessage) SetId(v string) {
	x.Id = v
}

func (x *UserFollowMessage) SetUserId(v string) {
	x.UserId = v
}

func (x *UserFollowMessage) SetFollowedUserId(v string) {
	x.FollowedUserId = v
}

func (x *UserFollowMessage) SetFollowUtcTimestampMs(v int64) {
	x.FollowUtcTimestampMs = v
}

func (x *UserFollowMessage) SetMetadata(v *StorageMetadataMessage) {
	x.Metadata = v
}

func (x *UserFollowMessage) SetUser(v *PublicUserMessage) {
	x.User = v
}

func (x *UserFollowMessage) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *UserFollowMessage) HasUser() bool {
	if x == nil {
		return false
	}
	return x.User != nil
}

func (x *UserFollowMessage) ClearMetadata() {
	x.Metadata = nil
}

func (x *UserFollowMessage) ClearUser() {
	x.User = nil
}

type UserFollowMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                   string
	UserId               string
	FollowedUserId       string
	FollowUtcTimestampMs int64
	Metadata             *StorageMetadataMessage
	User                 *PublicUserMessage
}

func (b0 UserFollowMessage_builder) Build() *UserFollowMessage {
	m0 := &UserFollowMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.UserId = b.UserId
	x.FollowedUserId = b.FollowedUserId
	x.FollowUtcTimestampMs = b.FollowUtcTimestampMs
	x.Metadata = b.Metadata
	x.User = b.User
	return m0
}

type UserSubscriptionMessage struct {
	state         protoimpl.MessageState  `protogen:"hybrid.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PodcastId     string                  `protobuf:"bytes,3,opt,name=podcast_id,json=podcastId,proto3" json:"podcast_id,omitempty"`
	Metadata      *StorageMetadataMessage `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Podcast       *PodcastMessage         `protobuf:"bytes,5,opt,name=podcast,proto3" json:"podcast,omitempty"` // this is optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSubscriptionMessage) Reset() {
	*x = UserSubscriptionMessage{}
	mi := &file_proto_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSubscriptionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSubscriptionMessage) ProtoMessage() {}

func (x *UserSubscriptionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserSubscriptionMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserSubscriptionMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSubscriptionMessage) GetPodcastId() string {
	if x != nil {
		return x.PodcastId
	}
	return ""
}

func (x *UserSubscriptionMessage) GetMetadata() *StorageMetadataMessage {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserSubscriptionMessage) GetPodcast() *PodcastMessage {
	if x != nil {
		return x.Podcast
	}
	return nil
}

func (x *UserSubscriptionMessage) SetId(v string) {
	x.Id = v
}

func (x *UserSubscriptionMessage) SetUserId(v string) {
	x.UserId = v
}

func (x *UserSubscriptionMessage) SetPodcastId(v string) {
	x.PodcastId = v
}

func (x *UserSubscriptionMessage) SetMetadata(v *StorageMetadataMessage) {
	x.Metadata = v
}

func (x *UserSubscriptionMessage) SetPodcast(v *PodcastMessage) {
	x.Podcast = v
}

func (x *UserSubscriptionMessage) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *UserSubscriptionMessage) HasPodcast() bool {
	if x == nil {
		return false
	}
	return x.Podcast != nil
}

func (x *UserSubscriptionMessage) ClearMetadata() {
	x.Metadata = nil
}

func (x *UserSubscriptionMessage) ClearPodcast() {
	x.Podcast = nil
}

type UserSubscriptionMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        string
	UserId    string
	PodcastId string
	Metadata  *StorageMetadataMessage
	Podcast   *PodcastMessage
}

func (b0 UserSubscriptionMessage_builder) Build() *UserSubscriptionMessage {
	m0 := &UserSubscriptionMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.UserId = b.UserId
	x.PodcastId = b.PodcastId
	x.Metadata = b.Metadata
	x.Podcast = b.Podcast
	return m0
}

type UserListenMessage struct {
	state           protoimpl.MessageState  `protogen:"hybrid.v1"`
	Id              string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EpisodeId       string                  `protobuf:"bytes,3,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	ListenTimestamp int64                   `protobuf:"varint,4,opt,name=listen_timestamp,json=listenTimestamp,proto3" json:"listen_timestamp,omitempty"`
	Seconds         int64                   `protobuf:"varint,5,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Completed       bool                    `protobuf:"varint,6,opt,name=completed,proto3" json:"completed,omitempty"`
	Episode         *EpisodeMessage         `protobuf:"bytes,7,opt,name=episode,proto3" json:"episode,omitempty"` // this is optional, used for feed items
	Metadata        *StorageMetadataMessage `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserListenMessage) Reset() {
	*x = UserListenMessage{}
	mi := &file_proto_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListenMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListenMessage) ProtoMessage() {}

func (x *UserListenMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserListenMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserListenMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserListenMessage) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *UserListenMessage) GetListenTimestamp() int64 {
	if x != nil {
		return x.ListenTimestamp
	}
	return 0
}

func (x *UserListenMessage) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *UserListenMessage) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *UserListenMessage) GetEpisode() *EpisodeMessage {
	if x != nil {
		return x.Episode
	}
	return nil
}

func (x *UserListenMessage) GetMetadata() *StorageMetadataMessage {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserListenMessage) SetId(v string) {
	x.Id = v
}

func (x *UserListenMessage) SetUserId(v string) {
	x.UserId = v
}

func (x *UserListenMessage) SetEpisodeId(v string) {
	x.EpisodeId = v
}

func (x *UserListenMessage) SetListenTimestamp(v int64) {
	x.ListenTimestamp = v
}

func (x *UserListenMessage) SetSeconds(v int64) {
	x.Seconds = v
}

func (x *UserListenMessage) SetCompleted(v bool) {
	x.Completed = v
}

func (x *UserListenMessage) SetEpisode(v *EpisodeMessage) {
	x.Episode = v
}

func (x *UserListenMessage) SetMetadata(v *StorageMetadataMessage) {
	x.Metadata = v
}

func (x *UserListenMessage) HasEpisode() bool {
	if x == nil {
		return false
	}
	return x.Episode != nil
}

func (x *UserListenMessage) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *UserListenMessage) ClearEpisode() {
	x.Episode = nil
}

func (x *UserListenMessage) ClearMetadata() {
	x.Metadata = nil
}

type UserListenMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id              string
	UserId          string
	EpisodeId       string
	ListenTimestamp int64
	Seconds         int64
	Completed       bool
	Episode         *EpisodeMessage
	Metadata        *StorageMetadataMessage
}

func (b0 UserListenMessage_builder) Build() *UserListenMessage {
	m0 := &UserListenMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.UserId = b.UserId
	x.EpisodeId = b.EpisodeId
	x.ListenTimestamp = b.ListenTimestamp
	x.Seconds = b.Seconds
	x.Completed = b.Completed
	x.Episode = b.Episode
	x.Metadata = b.Metadata
	return m0
}

type UserFeedItemEpisodeMessage struct {
	state   protoimpl.MessageState `protogen:"hybrid.v1"`
	Episode *EpisodeMessage        `protobuf:"bytes,1,opt,name=episode,proto3" json:"episode,omitempty"`
	// These are social items relating to followed users
	UserListens   []*PublicUserMessage `protobuf:"bytes,2,rep,name=user_listens,json=userListens,proto3" json:"user_listens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFeedItemEpisodeMessage) Reset() {
	*x = UserFeedItemEpisodeMessage{}
	mi := &file_proto_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFeedItemEpisodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFeedItemEpisodeMessage) ProtoMessage() {}

func (x *UserFeedItemEpisodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserFeedItemEpisodeMessage) GetEpisode() *EpisodeMessage {
	if x != nil {
		return x.Episode
	}
	return nil
}

func (x *UserFeedItemEpisodeMessage) GetUserListens() []*PublicUserMessage {
	if x != nil {
		return x.UserListens
	}
	return nil
}

func (x *UserFeedItemEpisodeMessage) SetEpisode(v *EpisodeMessage) {
	x.Episode = v
}

func (x *UserFeedItemEpisodeMessage) SetUserListens(v []*PublicUserMessage) {
	x.UserListens = v
}

func (x *UserFeedItemEpisodeMessage) HasEpisode() bool {
	if x == nil {
		return false
	}
	return x.Episode != nil
}

func (x *UserFeedItemEpisodeMessage) ClearEpisode() {
	x.Episode = nil
}

type UserFeedItemEpisodeMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Episode *EpisodeMessage
	// These are social items relating to followed users
	UserListens []*PublicUserMessage
}

func (b0 UserFeedItemEpisodeMessage_builder) Build() *UserFeedItemEpisodeMessage {
	m0 := &UserFeedItemEpisodeMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Episode = b.Episode
	x.UserListens = b.UserListens
	return m0
}

type UserFeedItemRecommendationMessage struct {
	state             protoimpl.MessageState `protogen:"hybrid.v1"`
	Episode           *EpisodeMessage        `protobuf:"bytes,1,opt,name=episode,proto3" json:"episode,omitempty"`
	Podcast           *PodcastMessage        `protobuf:"bytes,2,opt,name=podcast,proto3" json:"podcast,omitempty"`
	UserListens       []*PublicUserMessage   `protobuf:"bytes,3,rep,name=user_listens,json=userListens,proto3" json:"user_listens,omitempty"`
	UserSubscriptions []*PublicUserMessage   `protobuf:"bytes,4,rep,name=user_subscriptions,json=userSubscriptions,proto3" json:"user_subscriptions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserFeedItemRecommendationMessage) Reset() {
	*x = UserFeedItemRecommendationMessage{}
	mi := &file_proto_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFeedItemRecommendationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFeedItemRecommendationMessage) ProtoMessage() {}

func (x *UserFeedItemRecommendationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserFeedItemRecommendationMessage) GetEpisode() *EpisodeMessage {
	if x != nil {
		return x.Episode
	}
	return nil
}

func (x *UserFeedItemRecommendationMessage) GetPodcast() *PodcastMessage {
	if x != nil {
		return x.Podcast
	}
	return nil
}

func (x *UserFeedItemRecommendationMessage) GetUserListens() []*PublicUserMessage {
	if x != nil {
		return x.UserListens
	}
	return nil
}

func (x *UserFeedItemRecommendationMessage) GetUserSubscriptions() []*PublicUserMessage {
	if x != nil {
		return x.UserSubscriptions
	}
	return nil
}

func (x *UserFeedItemRecommendationMessage) SetEpisode(v *EpisodeMessage) {
	x.Episode = v
}

func (x *UserFeedItemRecommendationMessage) SetPodcast(v *PodcastMessage) {
	x.Podcast = v
}

func (x *UserFeedItemRecommendationMessage) SetUserListens(v []*PublicUserMessage) {
	x.UserListens = v
}

func (x *UserFeedItemRecommendationMessage) SetUserSubscriptions(v []*PublicUserMessage) {
	x.UserSubscriptions = v
}

func (x *UserFeedItemRecommendationMessage) HasEpisode() bool {
	if x == nil {
		return false
	}
	return x.Episode != nil
}

func (x *UserFeedItemRecommendationMessage) HasPodcast() bool {
	if x == nil {
		return false
	}
	return x.Podcast != nil
}

func (x *UserFeedItemRecommendationMessage) ClearEpisode() {
	x.Episode = nil
}

func (x *UserFeedItemRecommendationMessage) ClearPodcast() {
	x.Podcast = nil
}

type UserFeedItemRecommendationMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Episode           *EpisodeMessage
	Podcast           *PodcastMessage
	UserListens       []*PublicUserMessage
	UserSubscriptions []*PublicUserMessage
}

func (b0 UserFeedItemRecommendationMessage_builder) Build() *UserFeedItemRecommendationMessage {
	m0 := &UserFeedItemRecommendationMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Episode = b.Episode
	x.Podcast = b.Podcast
	x.UserListens = b.UserListens
	x.UserSubscriptions = b.UserSubscriptions
	return m0
}

type UserFeedItemMessage struct {
	state            protoimpl.MessageState               `protogen:"hybrid.v1"`
	EpisodeItem      *UserFeedItemEpisodeMessage          `protobuf:"bytes,1,opt,name=episode_item,json=episodeItem,proto3" json:"episode_item,omitempty"`
	RecommendedItems []*UserFeedItemRecommendationMessage `protobuf:"bytes,2,rep,name=recommended_items,json=recommendedItems,proto3" json:"recommended_items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserFeedItemMessage) Reset() {
	*x = UserFeedItemMessage{}
	mi := &file_proto_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFeedItemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFeedItemMessage) ProtoMessage() {}

func (x *UserFeedItemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserFeedItemMessage) GetEpisodeItem() *UserFeedItemEpisodeMessage {
	if x != nil {
		return x.EpisodeItem
	}
	return nil
}

func (x *UserFeedItemMessage) GetRecommendedItems() []*UserFeedItemRecommendationMessage {
	if x != nil {
		return x.RecommendedItems
	}
	return nil
}

func (x *UserFeedItemMessage) SetEpisodeItem(v *UserFeedItemEpisodeMessage) {
	x.EpisodeItem = v
}

func (x *UserFeedItemMessage) SetRecommendedItems(v []*UserFeedItemRecommendationMessage) {
	x.RecommendedItems = v
}

func (x *UserFeedItemMessage) HasEpisodeItem() bool {
	if x == nil {
		return false
	}
	return x.EpisodeItem != nil
}

func (x *UserFeedItemMessage) ClearEpisodeItem() {
	x.EpisodeItem = nil
}

type UserFeedItemMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EpisodeItem      *UserFeedItemEpisodeMessage
	RecommendedItems []*UserFeedItemRecommendationMessage
}

func (b0 UserFeedItemMessage_builder) Build() *UserFeedItemMessage {
	m0 := &UserFeedItemMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.EpisodeItem = b.EpisodeItem
	x.RecommendedItems = b.RecommendedItems
	return m0
}

type UserFeedMessage struct {
	state         protoimpl.MessageState  `protogen:"hybrid.v1"`
	UserId        string                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*UserFeedItemMessage  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *StorageMetadataMessage `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFeedMessage) Reset() {
	*x = UserFeedMessage{}
	mi := &file_proto_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFeedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFeedMessage) ProtoMessage() {}

func (x *UserFeedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserFeedMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserFeedMessage) GetItems() []*UserFeedItemMessage {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UserFeedMessage) GetMetadata() *StorageMetadataMessage {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserFeedMessage) SetUserId(v string) {
	x.UserId = v
}

func (x *UserFeedMessage) SetItems(v []*UserFeedItemMessage) {
	x.Items = v
}

func (x *UserFeedMessage) SetMetadata(v *StorageMetadataMessage) {
	x.Metadata = v
}

func (x *UserFeedMessage) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *UserFeedMessage) ClearMetadata() {
	x.Metadata = nil
}

type UserFeedMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId   string
	Items    []*UserFeedItemMessage
	Metadata *StorageMetadataMessage
}

func (b0 UserFeedMessage_builder) Build() *UserFeedMessage {
	m0 := &UserFeedMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.UserId = b.UserId
	x.Items = b.Items
	x.Metadata = b.Metadata
	return m0
}

// Search Results
type SearchResultMessage struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Only one of these should be filled out
	Podcast       *PodcastMessage `protobuf:"bytes,1,opt,name=podcast,proto3" json:"podcast,omitempty"`
	User          *UserMessage    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Episode       *EpisodeMessage `protobuf:"bytes,3,opt,name=episode,proto3" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResultMessage) Reset() {
	*x = SearchResultMessage{}
	mi := &file_proto_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultMessage) ProtoMessage() {}

func (x *SearchResultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SearchResultMessage) GetPodcast() *PodcastMessage {
	if x != nil {
		return x.Podcast
	}
	return nil
}

func (x *SearchResultMessage) GetUser() *UserMessage {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *SearchResultMessage) GetEpisode() *EpisodeMessage {
	if x != nil {
		return x.Episode
	}
	return nil
}

func (x *SearchResultMessage) SetPodcast(v *PodcastMessage) {
	x.Podcast = v
}

func (x *SearchResultMessage) SetUser(v *UserMessage) {
	x.User = v
}

func (x *SearchResultMessage) SetEpisode(v *EpisodeMessage) {
	x.Episode = v
}

func (x *SearchResultMessage) HasPodcast() bool {
	if x == nil {
		return false
	}
	return x.Podcast != nil
}

func (x *SearchResultMessage) HasUser() bool {
	if x == nil {
		return false
	}
	return x.User != nil
}

func (x *SearchResultMessage) HasEpisode() bool {
	if x == nil {
		return false
	}
	return x.Episode != nil
}

func (x *SearchResultMessage) ClearPodcast() {
	x.Podcast = nil
}

func (x *SearchResultMessage) ClearUser() {
	x.User = nil
}

func (x *SearchResultMessage) ClearEpisode() {
	x.Episode = nil
}

type SearchResultMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Only one of these should be filled out
	Podcast *PodcastMessage
	User    *UserMessage
	Episode *EpisodeMessage
}

func (b0 SearchResultMessage_builder) Build() *SearchResultMessage {
	m0 := &SearchResultMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Podcast = b.Podcast
	x.User = b.User
	x.Episode = b.Episode
	return m0
}

type SearchResultsMessage struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Results       []*SearchResultMessage `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // int64 num_results = 2;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResultsMessage) Reset() {
	*x = SearchResultsMessage{}
	mi := &file_proto_common_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResultsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultsMessage) ProtoMessage() {}

func (x *SearchResultsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SearchResultsMessage) GetResults() []*SearchResultMessage {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResultsMessage) SetResults(v []*SearchResultMessage) {
	x.Results = v
}

type SearchResultsMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Results []*SearchResultMessage
}

func (b0 SearchResultsMessage_builder) Build() *SearchResultsMessage {
	m0 := &SearchResultsMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Results = b.Results
	return m0
}

type UserDownloadMessage struct {
	state         protoimpl.MessageState  `protogen:"hybrid.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EpisodeId     string                  `protobuf:"bytes,2,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	FilePath      string                  `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	IsDownloaded  bool                    `protobuf:"varint,4,opt,name=is_downloaded,json=isDownloaded,proto3" json:"is_downloaded,omitempty"`
	Metadata      *StorageMetadataMessage `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDownloadMessage) Reset() {
	*x = UserDownloadMessage{}
	mi := &file_proto_common_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDownloadMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDownloadMessage) ProtoMessage() {}

func (x *UserDownloadMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserDownloadMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserDownloadMessage) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *UserDownloadMessage) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UserDownloadMessage) GetIsDownloaded() bool {
	if x != nil {
		return x.IsDownloaded
	}
	return false
}

func (x *UserDownloadMessage) GetMetadata() *StorageMetadataMessage {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserDownloadMessage) SetId(v string) {
	x.Id = v
}

func (x *UserDownloadMessage) SetEpisodeId(v string) {
	x.EpisodeId = v
}

func (x *UserDownloadMessage) SetFilePath(v string) {
	x.FilePath = v
}

func (x *UserDownloadMessage) SetIsDownloaded(v bool) {
	x.IsDownloaded = v
}

func (x *UserDownloadMessage) SetMetadata(v *StorageMetadataMessage) {
	x.Metadata = v
}

func (x *UserDownloadMessage) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *UserDownloadMessage) ClearMetadata() {
	x.Metadata = nil
}

type UserDownloadMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id           string
	EpisodeId    string
	FilePath     string
	IsDownloaded bool
	Metadata     *StorageMetadataMessage
}

func (b0 UserDownloadMessage_builder) Build() *UserDownloadMessage {
	m0 := &UserDownloadMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.EpisodeId = b.EpisodeId
	x.FilePath = b.FilePath
	x.IsDownloaded = b.IsDownloaded
	x.Metadata = b.Metadata
	return m0
}

type UserContactsMessage struct {
	state         protoimpl.MessageState  `protogen:"hybrid.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Contacts      []*UserContactMessage   `protobuf:"bytes,3,rep,name=contacts,proto3" json:"contacts,omitempty"`
	Metadata      *StorageMetadataMessage `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContactsMessage) Reset() {
	*x = UserContactsMessage{}
	mi := &file_proto_common_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContactsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContactsMessage) ProtoMessage() {}

func (x *UserContactsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserContactsMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserContactsMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserContactsMessage) GetContacts() []*UserContactMessage {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *UserContactsMessage) GetMetadata() *StorageMetadataMessage {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserContactsMessage) SetId(v string) {
	x.Id = v
}

func (x *UserContactsMessage) SetUserId(v string) {
	x.UserId = v
}

func (x *UserContactsMessage) SetContacts(v []*UserContactMessage) {
	x.Contacts = v
}

func (x *UserContactsMessage) SetMetadata(v *StorageMetadataMessage) {
	x.Metadata = v
}

func (x *UserContactsMessage) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *UserContactsMessage) ClearMetadata() {
	x.Metadata = nil
}

type UserContactsMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id       string
	UserId   string
	Contacts []*UserContactMessage
	Metadata *StorageMetadataMessage
}

func (b0 UserContactsMessage_builder) Build() *UserContactsMessage {
	m0 := &UserContactsMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.UserId = b.UserId
	x.Contacts = b.Contacts
	x.Metadata = b.Metadata
	return m0
}

type UserContactMessage struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// This is the contact id from their phone
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PhoneNumber   string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContactMessage) Reset() {
	*x = UserContactMessage{}
	mi := &file_proto_common_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContactMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContactMessage) ProtoMessage() {}

func (x *UserContactMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserContactMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserContactMessage) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserContactMessage) SetId(v string) {
	x.Id = v
}

func (x *UserContactMessage) SetPhoneNumber(v string) {
	x.PhoneNumber = v
}

type UserContactMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// This is the contact id from their phone
	Id          string
	PhoneNumber string
}

func (b0 UserContactMessage_builder) Build() *UserContactMessage {
	m0 := &UserContactMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.PhoneNumber = b.PhoneNumber
	return m0
}

type SettingsMessage struct {
	state          protoimpl.MessageState  `protogen:"hybrid.v1"`
	Id             string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata       *StorageMetadataMessage `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	EnablePlaylist bool                    `protobuf:"varint,3,opt,name=enable_playlist,json=enablePlaylist,proto3" json:"enable_playlist,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SettingsMessage) Reset() {
	*x = SettingsMessage{}
	mi := &file_proto_common_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsMessage) ProtoMessage() {}

func (x *SettingsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SettingsMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SettingsMessage) GetMetadata() *StorageMetadataMessage {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SettingsMessage) GetEnablePlaylist() bool {
	if x != nil {
		return x.EnablePlaylist
	}
	return false
}

func (x *SettingsMessage) SetId(v string) {
	x.Id = v
}

func (x *SettingsMessage) SetMetadata(v *StorageMetadataMessage) {
	x.Metadata = v
}

func (x *SettingsMessage) SetEnablePlaylist(v bool) {
	x.EnablePlaylist = v
}

func (x *SettingsMessage) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *SettingsMessage) ClearMetadata() {
	x.Metadata = nil
}

type SettingsMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id             string
	Metadata       *StorageMetadataMessage
	EnablePlaylist bool
}

func (b0 SettingsMessage_builder) Build() *SettingsMessage {
	m0 := &SettingsMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.EnablePlaylist = b.EnablePlaylist
	return m0
}

var file_proto_common_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "resonate.index",
		Tag:           "varint,50000,opt,name=index",
		Filename:      "proto/common.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Whether to index the field in the DB
	//
	// optional bool index = 50000;
	E_Index = &file_proto_common_proto_extTypes[0]
)

var File_proto_common_proto protoreflect.FileDescriptor

const file_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x12proto/common.proto\x12\bresonate\x1a google/protobuf/descriptor.proto\"\x91\x01\n" +
	"\x16StorageMetadataMessage\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x01 \x01(\bR\tisDeleted\x12+\n" +
	"\x11updated_timestamp\x18\x02 \x01(\x03R\x10updatedTimestamp\x12+\n" +
	"\x11created_timestamp\x18\x03 \x01(\x03R\x10createdTimestamp\"\x97\x03\n" +
	"\x0ePodcastMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\x05title\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1c\n" +
	"\x06author\x18\x06 \x01(\tB\x04\x80\xb5\x18\x01R\x06author\x124\n" +
	"\bepisodes\x18\a \x03(\v2\x18.resonate.EpisodeMessageR\bepisodes\x12<\n" +
	"\bmetadata\x18\b \x01(\v2 .resonate.StorageMetadataMessageR\bmetadata\x12>\n" +
	"\x18latest_episode_timestamp\x18\t \x01(\x03B\x04\x80\xb5\x18\x01R\x16latestEpisodeTimestamp\x126\n" +
	"\x14last_fetch_timestamp\x18\n" +
	" \x01(\x03B\x04\x80\xb5\x18\x01R\x12lastFetchTimestamp\"\x96\x03\n" +
	"\x0eEpisodeMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\n" +
	"podcast_id\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\tpodcastId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\taudio_url\x18\x05 \x01(\tR\baudioUrl\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x121\n" +
	"\x11publish_timestamp\x18\b \x01(\x03B\x04\x80\xb5\x18\x01R\x10publishTimestamp\x12)\n" +
	"\x10duration_seconds\x18\t \x01(\x03R\x0fdurationSeconds\x12%\n" +
	"\x0eepisode_number\x18\n" +
	" \x01(\x03R\repisodeNumber\x12\x1a\n" +
	"\bexplicit\x18\v \x01(\bR\bexplicit\x12<\n" +
	"\bmetadata\x18\f \x01(\v2 .resonate.StorageMetadataMessageR\bmetadata\"V\n" +
	"\fTokenMessage\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x120\n" +
	"\x14expiry_utc_timestamp\x18\x02 \x01(\x03R\x12expiryUtcTimestamp\"\xf6\x01\n" +
	"\fLoginAttempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\fphone_number\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\vphoneNumber\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12<\n" +
	"\bmetadata\x18\x04 \x01(\v2 .resonate.StorageMetadataMessageR\bmetadata\x120\n" +
	"\x14expiry_utc_timestamp\x18\x05 \x01(\x03R\x12expiryUtcTimestamp\x12!\n" +
	"\fnum_attempts\x18\x06 \x01(\x03R\vnumAttempts\"\xb7\x01\n" +
	"\x12UserStorageMessage\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.resonate.UserMessageR\x04user\x129\n" +
	"\faccess_token\x18\x02 \x01(\v2\x16.resonate.TokenMessageR\vaccessToken\x12;\n" +
	"\rrefresh_token\x18\x03 \x01(\v2\x16.resonate.TokenMessageR\frefreshToken\"\xb3\x01\n" +
	"\x14RefreshTokensMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\auser_id\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\x06userId\x12.\n" +
	"\x06tokens\x18\x03 \x03(\v2\x16.resonate.TokenMessageR\x06tokens\x12<\n" +
	"\bmetadata\x18\x04 \x01(\v2 .resonate.StorageMetadataMessageR\bmetadata\"\xdb\x03\n" +
	"\vUserMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\n" +
	" \x01(\tR\vphoneNumber\x124\n" +
	"\x16encrypted_phone_number\x18\v \x01(\tR\x14encryptedPhoneNumber\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12G\n" +
	"\rsubscriptions\x18\x05 \x03(\v2!.resonate.UserSubscriptionMessageR\rsubscriptions\x125\n" +
	"\alistens\x18\x06 \x03(\v2\x1b.resonate.UserListenMessageR\alistens\x129\n" +
	"\tfollowing\x18\a \x03(\v2\x1b.resonate.UserFollowMessageR\tfollowing\x12#\n" +
	"\rnum_followers\x18\b \x01(\x03R\fnumFollowers\x12<\n" +
	"\bmetadata\x18\t \x01(\v2 .resonate.StorageMetadataMessageR\bmetadata\"T\n" +
	"\x11PublicUserMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\"\x98\x02\n" +
	"\x11UserFollowMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\auser_id\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\x06userId\x12.\n" +
	"\x10followed_user_id\x18\x03 \x01(\tB\x04\x80\xb5\x18\x01R\x0efollowedUserId\x125\n" +
	"\x17follow_utc_timestamp_ms\x18\x04 \x01(\x03R\x14followUtcTimestampMs\x12<\n" +
	"\bmetadata\x18\x05 \x01(\v2 .resonate.StorageMetadataMessageR\bmetadata\x12/\n" +
	"\x04user\x18\x06 \x01(\v2\x1b.resonate.PublicUserMessageR\x04user\"\xdf\x01\n" +
	"\x17UserSubscriptionMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\auser_id\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\x06userId\x12#\n" +
	"\n" +
	"podcast_id\x18\x03 \x01(\tB\x04\x80\xb5\x18\x01R\tpodcastId\x12<\n" +
	"\bmetadata\x18\x04 \x01(\v2 .resonate.StorageMetadataMessageR\bmetadata\x122\n" +
	"\apodcast\x18\x05 \x01(\v2\x18.resonate.PodcastMessageR\apodcast\"\xc8\x02\n" +
	"\x11UserListenMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\auser_id\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\x06userId\x12#\n" +
	"\n" +
	"episode_id\x18\x03 \x01(\tB\x04\x80\xb5\x18\x01R\tepisodeId\x12/\n" +
	"\x10listen_timestamp\x18\x04 \x01(\x03B\x04\x80\xb5\x18\x01R\x0flistenTimestamp\x12\x18\n" +
	"\aseconds\x18\x05 \x01(\x03R\aseconds\x12\"\n" +
	"\tcompleted\x18\x06 \x01(\bB\x04\x80\xb5\x18\x01R\tcompleted\x122\n" +
	"\aepisode\x18\a \x01(\v2\x18.resonate.EpisodeMessageR\aepisode\x12<\n" +
	"\bmetadata\x18\b \x01(\v2 .resonate.StorageMetadataMessageR\bmetadata\"\x90\x01\n" +
	"\x1aUserFeedItemEpisodeMessage\x122\n" +
	"\aepisode\x18\x01 \x01(\v2\x18.resonate.EpisodeMessageR\aepisode\x12>\n" +
	"\fuser_listens\x18\x02 \x03(\v2\x1b.resonate.PublicUserMessageR\vuserListens\"\x97\x02\n" +
	"!UserFeedItemRecommendationMessage\x122\n" +
	"\aepisode\x18\x01 \x01(\v2\x18.resonate.EpisodeMessageR\aepisode\x122\n" +
	"\apodcast\x18\x02 \x01(\v2\x18.resonate.PodcastMessageR\apodcast\x12>\n" +
	"\fuser_listens\x18\x03 \x03(\v2\x1b.resonate.PublicUserMessageR\vuserListens\x12J\n" +
	"\x12user_subscriptions\x18\x04 \x03(\v2\x1b.resonate.PublicUserMessageR\x11userSubscriptions\"\xb8\x01\n" +
	"\x13UserFeedItemMessage\x12G\n" +
	"\fepisode_item\x18\x01 \x01(\v2$.resonate.UserFeedItemEpisodeMessageR\vepisodeItem\x12X\n" +
	"\x11recommended_items\x18\x02 \x03(\v2+.resonate.UserFeedItemRecommendationMessageR\x10recommendedItems\"\xa3\x01\n" +
	"\x0fUserFeedMessage\x12\x1d\n" +
	"\auser_id\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\x06userId\x123\n" +
	"\x05items\x18\x02 \x03(\v2\x1d.resonate.UserFeedItemMessageR\x05items\x12<\n" +
	"\bmetadata\x18\x03 \x01(\v2 .resonate.StorageMetadataMessageR\bmetadata\"\xa8\x01\n" +
	"\x13SearchResultMessage\x122\n" +
	"\apodcast\x18\x01 \x01(\v2\x18.resonate.PodcastMessageR\apodcast\x12)\n" +
	"\x04user\x18\x02 \x01(\v2\x15.resonate.UserMessageR\x04user\x122\n" +
	"\aepisode\x18\x03 \x01(\v2\x18.resonate.EpisodeMessageR\aepisode\"O\n" +
	"\x14SearchResultsMessage\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.resonate.SearchResultMessageR\aresults\"\xca\x01\n" +
	"\x13UserDownloadMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\n" +
	"episode_id\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\tepisodeId\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12#\n" +
	"\ris_downloaded\x18\x04 \x01(\bR\fisDownloaded\x12<\n" +
	"\bmetadata\x18\x05 \x01(\v2 .resonate.StorageMetadataMessageR\bmetadata\"\xbc\x01\n" +
	"\x13UserContactsMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\auser_id\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\x06userId\x128\n" +
	"\bcontacts\x18\x03 \x03(\v2\x1c.resonate.UserContactMessageR\bcontacts\x12<\n" +
	"\bmetadata\x18\x04 \x01(\v2 .resonate.StorageMetadataMessageR\bmetadata\"G\n" +
	"\x12UserContactMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\"\x8e\x01\n" +
	"\x0fSettingsMessage\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\x02id\x12<\n" +
	"\bmetadata\x18\x02 \x01(\v2 .resonate.StorageMetadataMessageR\bmetadata\x12'\n" +
	"\x0fenable_playlist\x18\x03 \x01(\bR\x0eenablePlaylist:5\n" +
	"\x05index\x12\x1d.google.protobuf.FieldOptions\x18І\x03 \x01(\bR\x05indexB*Z(github.com/dghwood/resonate/server/protob\x06proto3"

var file_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_common_proto_goTypes = []any{
	(*StorageMetadataMessage)(nil),            // 0: resonate.StorageMetadataMessage
	(*PodcastMessage)(nil),                    // 1: resonate.PodcastMessage
	(*EpisodeMessage)(nil),                    // 2: resonate.EpisodeMessage
	(*TokenMessage)(nil),                      // 3: resonate.TokenMessage
	(*LoginAttempt)(nil),                      // 4: resonate.LoginAttempt
	(*UserStorageMessage)(nil),                // 5: resonate.UserStorageMessage
	(*RefreshTokensMessage)(nil),              // 6: resonate.RefreshTokensMessage
	(*UserMessage)(nil),                       // 7: resonate.UserMessage
	(*PublicUserMessage)(nil),                 // 8: resonate.PublicUserMessage
	(*UserFollowMessage)(nil),                 // 9: resonate.UserFollowMessage
	(*UserSubscriptionMessage)(nil),           // 10: resonate.UserSubscriptionMessage
	(*UserListenMessage)(nil),                 // 11: resonate.UserListenMessage
	(*UserFeedItemEpisodeMessage)(nil),        // 12: resonate.UserFeedItemEpisodeMessage
	(*UserFeedItemRecommendationMessage)(nil), // 13: resonate.UserFeedItemRecommendationMessage
	(*UserFeedItemMessage)(nil),               // 14: resonate.UserFeedItemMessage
	(*UserFeedMessage)(nil),                   // 15: resonate.UserFeedMessage
	(*SearchResultMessage)(nil),               // 16: resonate.SearchResultMessage
	(*SearchResultsMessage)(nil),              // 17: resonate.SearchResultsMessage
	(*UserDownloadMessage)(nil),               // 18: resonate.UserDownloadMessage
	(*UserContactsMessage)(nil),               // 19: resonate.UserContactsMessage
	(*UserContactMessage)(nil),                // 20: resonate.UserContactMessage
	(*SettingsMessage)(nil),                   // 21: resonate.SettingsMessage
	(*descriptorpb.FieldOptions)(nil),         // 22: google.protobuf.FieldOptions
}
var file_proto_common_proto_depIdxs = []int32{
	2,  // 0: resonate.PodcastMessage.episodes:type_name -> resonate.EpisodeMessage
	0,  // 1: resonate.PodcastMessage.metadata:type_name -> resonate.StorageMetadataMessage
	0,  // 2: resonate.EpisodeMessage.metadata:type_name -> resonate.StorageMetadataMessage
	0,  // 3: resonate.LoginAttempt.metadata:type_name -> resonate.StorageMetadataMessage
	7,  // 4: resonate.UserStorageMessage.user:type_name -> resonate.UserMessage
	3,  // 5: resonate.UserStorageMessage.access_token:type_name -> resonate.TokenMessage
	3,  // 6: resonate.UserStorageMessage.refresh_token:type_name -> resonate.TokenMessage
	3,  // 7: resonate.RefreshTokensMessage.tokens:type_name -> resonate.TokenMessage
	0,  // 8: resonate.RefreshTokensMessage.metadata:type_name -> resonate.StorageMetadataMessage
	10, // 9: resonate.UserMessage.subscriptions:type_name -> resonate.UserSubscriptionMessage
	11, // 10: resonate.UserMessage.listens:type_name -> resonate.UserListenMessage
	9,  // 11: resonate.UserMessage.following:type_name -> resonate.UserFollowMessage
	0,  // 12: resonate.UserMessage.metadata:type_name -> resonate.StorageMetadataMessage
	0,  // 13: resonate.UserFollowMessage.metadata:type_name -> resonate.StorageMetadataMessage
	8,  // 14: resonate.UserFollowMessage.user:type_name -> resonate.PublicUserMessage
	0,  // 15: resonate.UserSubscriptionMessage.metadata:type_name -> resonate.StorageMetadataMessage
	1,  // 16: resonate.UserSubscriptionMessage.podcast:type_name -> resonate.PodcastMessage
	2,  // 17: resonate.UserListenMessage.episode:type_name -> resonate.EpisodeMessage
	0,  // 18: resonate.UserListenMessage.metadata:type_name -> resonate.StorageMetadataMessage
	2,  // 19: resonate.UserFeedItemEpisodeMessage.episode:type_name -> resonate.EpisodeMessage
	8,  // 20: resonate.UserFeedItemEpisodeMessage.user_listens:type_name -> resonate.PublicUserMessage
	2,  // 21: resonate.UserFeedItemRecommendationMessage.episode:type_name -> resonate.EpisodeMessage
	1,  // 22: resonate.UserFeedItemRecommendationMessage.podcast:type_name -> resonate.PodcastMessage
	8,  // 23: resonate.UserFeedItemRecommendationMessage.user_listens:type_name -> resonate.PublicUserMessage
	8,  // 24: resonate.UserFeedItemRecommendationMessage.user_subscriptions:type_name -> resonate.PublicUserMessage
	12, // 25: resonate.UserFeedItemMessage.episode_item:type_name -> resonate.UserFeedItemEpisodeMessage
	13, // 26: resonate.UserFeedItemMessage.recommended_items:type_name -> resonate.UserFeedItemRecommendationMessage
	14, // 27: resonate.UserFeedMessage.items:type_name -> resonate.UserFeedItemMessage
	0,  // 28: resonate.UserFeedMessage.metadata:type_name -> resonate.StorageMetadataMessage
	1,  // 29: resonate.SearchResultMessage.podcast:type_name -> resonate.PodcastMessage
	7,  // 30: resonate.SearchResultMessage.user:type_name -> resonate.UserMessage
	2,  // 31: resonate.SearchResultMessage.episode:type_name -> resonate.EpisodeMessage
	16, // 32: resonate.SearchResultsMessage.results:type_name -> resonate.SearchResultMessage
	0,  // 33: resonate.UserDownloadMessage.metadata:type_name -> resonate.StorageMetadataMessage
	20, // 34: resonate.UserContactsMessage.contacts:type_name -> resonate.UserContactMessage
	0,  // 35: resonate.UserContactsMessage.metadata:type_name -> resonate.StorageMetadataMessage
	0,  // 36: resonate.SettingsMessage.metadata:type_name -> resonate.StorageMetadataMessage
	22, // 37: resonate.index:extendee -> google.protobuf.FieldOptions
	38, // [38:38] is the sub-list for method output_type
	38, // [38:38] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	37, // [37:38] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		MessageInfos:      file_proto_common_proto_msgTypes,
		ExtensionInfos:    file_proto_common_proto_extTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
