// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/errors.proto

//go:build !protoopaque

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorEnum int32

const (
	ErrorEnum_ERROR_UNKNOWN              ErrorEnum = 0
	ErrorEnum_ERROR_INTERNAL             ErrorEnum = 1
	ErrorEnum_ERROR_PERMISSION_DENIED    ErrorEnum = 2
	ErrorEnum_ERROR_INVALID_CREDENTIALS  ErrorEnum = 3
	ErrorEnum_ERROR_TOO_MANY_ATTEMPTS    ErrorEnum = 4
	ErrorEnum_ERROR_TIME_EXPIRED         ErrorEnum = 5
	ErrorEnum_ERROR_UPLOAD_SIZE_EXCEEDED ErrorEnum = 6
)

// Enum value maps for ErrorEnum.
var (
	ErrorEnum_name = map[int32]string{
		0: "ERROR_UNKNOWN",
		1: "ERROR_INTERNAL",
		2: "ERROR_PERMISSION_DENIED",
		3: "ERROR_INVALID_CREDENTIALS",
		4: "ERROR_TOO_MANY_ATTEMPTS",
		5: "ERROR_TIME_EXPIRED",
		6: "ERROR_UPLOAD_SIZE_EXCEEDED",
	}
	ErrorEnum_value = map[string]int32{
		"ERROR_UNKNOWN":              0,
		"ERROR_INTERNAL":             1,
		"ERROR_PERMISSION_DENIED":    2,
		"ERROR_INVALID_CREDENTIALS":  3,
		"ERROR_TOO_MANY_ATTEMPTS":    4,
		"ERROR_TIME_EXPIRED":         5,
		"ERROR_UPLOAD_SIZE_EXCEEDED": 6,
	}
)

func (x ErrorEnum) Enum() *ErrorEnum {
	p := new(ErrorEnum)
	*p = x
	return p
}

func (x ErrorEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorEnum) Type() protoreflect.EnumType {
	return &file_proto_errors_proto_enumTypes[0]
}

func (x ErrorEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_proto_errors_proto protoreflect.FileDescriptor

const file_proto_errors_proto_rawDesc = "" +
	"\n" +
	"\x12proto/errors.proto\x12\bresonate*\xc3\x01\n" +
	"\tErrorEnum\x12\x11\n" +
	"\rERROR_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eERROR_INTERNAL\x10\x01\x12\x1b\n" +
	"\x17ERROR_PERMISSION_DENIED\x10\x02\x12\x1d\n" +
	"\x19ERROR_INVALID_CREDENTIALS\x10\x03\x12\x1b\n" +
	"\x17ERROR_TOO_MANY_ATTEMPTS\x10\x04\x12\x16\n" +
	"\x12ERROR_TIME_EXPIRED\x10\x05\x12\x1e\n" +
	"\x1aERROR_UPLOAD_SIZE_EXCEEDED\x10\x06B#Z!github.com/dghwood/resonate/protob\x06proto3"

var file_proto_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_errors_proto_goTypes = []any{
	(ErrorEnum)(0), // 0: resonate.ErrorEnum
}
var file_proto_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_errors_proto_init() }
func file_proto_errors_proto_init() {
	if File_proto_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_errors_proto_rawDesc), len(file_proto_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_errors_proto_goTypes,
		DependencyIndexes: file_proto_errors_proto_depIdxs,
		EnumInfos:         file_proto_errors_proto_enumTypes,
	}.Build()
	File_proto_errors_proto = out.File
	file_proto_errors_proto_goTypes = nil
	file_proto_errors_proto_depIdxs = nil
}
