// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/logging.proto

//go:build !protoopaque

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Next Tag: 9
type ApiEventMessage struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	TimestampUsec int64                  `protobuf:"varint,1,opt,name=timestamp_usec,json=timestampUsec,proto3" json:"timestamp_usec,omitempty"`
	// Get this from "cloud.google.com/go/compute/metadata" on startup
	InstanceId string `protobuf:"bytes,8,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Need to add a binary version for the SERVER
	BinaryVersion string        `protobuf:"bytes,9,opt,name=binary_version,json=binaryVersion,proto3" json:"binary_version,omitempty"`
	ApiPath       string        `protobuf:"bytes,2,opt,name=api_path,json=apiPath,proto3" json:"api_path,omitempty"`
	RequestInfo   *RequestInfo  `protobuf:"bytes,3,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	ResponseInfo  *ResponseInfo `protobuf:"bytes,4,opt,name=response_info,json=responseInfo,proto3" json:"response_info,omitempty"`
	// X-Cloud-Trace-Context header
	TraceId string `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// X-Forwarded-For
	Ips string `protobuf:"bytes,6,opt,name=ips,proto3" json:"ips,omitempty"`
	// When the response was written
	ResponseTimestampUsec int64 `protobuf:"varint,7,opt,name=response_timestamp_usec,json=responseTimestampUsec,proto3" json:"response_timestamp_usec,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ApiEventMessage) Reset() {
	*x = ApiEventMessage{}
	mi := &file_proto_logging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiEventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiEventMessage) ProtoMessage() {}

func (x *ApiEventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ApiEventMessage) GetTimestampUsec() int64 {
	if x != nil {
		return x.TimestampUsec
	}
	return 0
}

func (x *ApiEventMessage) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ApiEventMessage) GetBinaryVersion() string {
	if x != nil {
		return x.BinaryVersion
	}
	return ""
}

func (x *ApiEventMessage) GetApiPath() string {
	if x != nil {
		return x.ApiPath
	}
	return ""
}

func (x *ApiEventMessage) GetRequestInfo() *RequestInfo {
	if x != nil {
		return x.RequestInfo
	}
	return nil
}

func (x *ApiEventMessage) GetResponseInfo() *ResponseInfo {
	if x != nil {
		return x.ResponseInfo
	}
	return nil
}

func (x *ApiEventMessage) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ApiEventMessage) GetIps() string {
	if x != nil {
		return x.Ips
	}
	return ""
}

func (x *ApiEventMessage) GetResponseTimestampUsec() int64 {
	if x != nil {
		return x.ResponseTimestampUsec
	}
	return 0
}

func (x *ApiEventMessage) SetTimestampUsec(v int64) {
	x.TimestampUsec = v
}

func (x *ApiEventMessage) SetInstanceId(v string) {
	x.InstanceId = v
}

func (x *ApiEventMessage) SetBinaryVersion(v string) {
	x.BinaryVersion = v
}

func (x *ApiEventMessage) SetApiPath(v string) {
	x.ApiPath = v
}

func (x *ApiEventMessage) SetRequestInfo(v *RequestInfo) {
	x.RequestInfo = v
}

func (x *ApiEventMessage) SetResponseInfo(v *ResponseInfo) {
	x.ResponseInfo = v
}

func (x *ApiEventMessage) SetTraceId(v string) {
	x.TraceId = v
}

func (x *ApiEventMessage) SetIps(v string) {
	x.Ips = v
}

func (x *ApiEventMessage) SetResponseTimestampUsec(v int64) {
	x.ResponseTimestampUsec = v
}

func (x *ApiEventMessage) HasRequestInfo() bool {
	if x == nil {
		return false
	}
	return x.RequestInfo != nil
}

func (x *ApiEventMessage) HasResponseInfo() bool {
	if x == nil {
		return false
	}
	return x.ResponseInfo != nil
}

func (x *ApiEventMessage) ClearRequestInfo() {
	x.RequestInfo = nil
}

func (x *ApiEventMessage) ClearResponseInfo() {
	x.ResponseInfo = nil
}

type ApiEventMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TimestampUsec int64
	// Get this from "cloud.google.com/go/compute/metadata" on startup
	InstanceId string
	// Need to add a binary version for the SERVER
	BinaryVersion string
	ApiPath       string
	RequestInfo   *RequestInfo
	ResponseInfo  *ResponseInfo
	// X-Cloud-Trace-Context header
	TraceId string
	// X-Forwarded-For
	Ips string
	// When the response was written
	ResponseTimestampUsec int64
}

func (b0 ApiEventMessage_builder) Build() *ApiEventMessage {
	m0 := &ApiEventMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.TimestampUsec = b.TimestampUsec
	x.InstanceId = b.InstanceId
	x.BinaryVersion = b.BinaryVersion
	x.ApiPath = b.ApiPath
	x.RequestInfo = b.RequestInfo
	x.ResponseInfo = b.ResponseInfo
	x.TraceId = b.TraceId
	x.Ips = b.Ips
	x.ResponseTimestampUsec = b.ResponseTimestampUsec
	return m0
}

var File_proto_logging_proto protoreflect.FileDescriptor

const file_proto_logging_proto_rawDesc = "" +
	"\n" +
	"\x13proto/logging.proto\x12\x10resonate.logging\x1a\x0fproto/api.proto\"\xff\x02\n" +
	"\x0fApiEventMessage\x12%\n" +
	"\x0etimestamp_usec\x18\x01 \x01(\x03R\rtimestampUsec\x12\x1f\n" +
	"\vinstance_id\x18\b \x01(\tR\n" +
	"instanceId\x12%\n" +
	"\x0ebinary_version\x18\t \x01(\tR\rbinaryVersion\x12\x19\n" +
	"\bapi_path\x18\x02 \x01(\tR\aapiPath\x12<\n" +
	"\frequest_info\x18\x03 \x01(\v2\x19.resonate.api.RequestInfoR\vrequestInfo\x12?\n" +
	"\rresponse_info\x18\x04 \x01(\v2\x1a.resonate.api.ResponseInfoR\fresponseInfo\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x10\n" +
	"\x03ips\x18\x06 \x01(\tR\x03ips\x126\n" +
	"\x17response_timestamp_usec\x18\a \x01(\x03R\x15responseTimestampUsecB#Z!github.com/dghwood/resonate/protob\x06proto3"

var file_proto_logging_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_logging_proto_goTypes = []any{
	(*ApiEventMessage)(nil), // 0: resonate.logging.ApiEventMessage
	(*RequestInfo)(nil),     // 1: resonate.api.RequestInfo
	(*ResponseInfo)(nil),    // 2: resonate.api.ResponseInfo
}
var file_proto_logging_proto_depIdxs = []int32{
	1, // 0: resonate.logging.ApiEventMessage.request_info:type_name -> resonate.api.RequestInfo
	2, // 1: resonate.logging.ApiEventMessage.response_info:type_name -> resonate.api.ResponseInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_logging_proto_init() }
func file_proto_logging_proto_init() {
	if File_proto_logging_proto != nil {
		return
	}
	file_proto_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logging_proto_rawDesc), len(file_proto_logging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_logging_proto_goTypes,
		DependencyIndexes: file_proto_logging_proto_depIdxs,
		MessageInfos:      file_proto_logging_proto_msgTypes,
	}.Build()
	File_proto_logging_proto = out.File
	file_proto_logging_proto_goTypes = nil
	file_proto_logging_proto_depIdxs = nil
}
